service: dokan-gg-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'production'}
  region: ap-southeast-1
  timeout: 300
  memorySize: 2048
  environment:
    NODE_ENV: production
    MONGODB_URL: mongodb+srv://poket-dokan-user:6XGLsXHlT5ApKZhW@dokan-gg-cluster.y7nxewc.mongodb.net/dokan-gg-production?retryWrites=true&w=majority
    JWT_SECRET: 6XGLsXHlT5ApKZhW
    APP_BASE_URL: https://dokan.gg
    SENDGRID_API_KEY: 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
    FROM_EMAIL: "No Reply <no-reply@dokan.gg>"
    AWS_ACCESS_KEY_ID: AKIARYRWBLEN3K5HI47G
    AWS_SECRET_ACCESS_KEY: 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
    AWS_BUCKET: cdn.dokan.gg
    AWS_REGION: ap-southeast-1
    S3_URL: https://s3.ap-southeast-1.amazonaws.com/cdn.dokan.gg/
    TINIFY_KEY: 4XJ9fyhM0tvwwGVDnJkCnB1rzxCqvsCW

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
