const express = require("express");
const route = express.Router();

const Category = require("../../models/category");

route
  .get("/", async (req, res) => {
    const { sort = "", range = "", filter = "{}", companyId } = req.query;
    const rangeExp = range && JSON.parse(range);

    try {
      const categories = await Category.find({ company: companyId })
        .populate("company")
        .limit(rangeExp.length && rangeExp[1] - rangeExp[0] + 1)
        .skip(rangeExp.length && rangeExp[0])
        .sort(sort);

      return res.status(200).json(categories);
    } catch (err) {
      console.log(err);
      return res.status(500).send(err);
    }
  })
  .get("/count", async (req, res) => {
    try {
      const count = await Category.countDocuments({ user: req.user._id });

      return res.status(200).json(count);
    } catch (err) {
      console.log(err);
      return res.status(500).send(err);
    }
  })
  .get("/:id", async (req, res) => {
    try {
      const category = await Category.findByIdAndUpdate(req.params.id, {
        $inc: { view: 1 },
      });

      return res.status(200).json(category);
    } catch (err) {
      console.log(err);
      res.status(500).send({ error: "Category does not exist." });
    }
  })
  .post("/", async (req, res) => {
    try {
      const category = await Category.create({
        ...req.body,
        createdBy: req?.user?._id,
      });

      return res.status(200).json(category);
    } catch (err) {
      console.log(err);
      res.status(500).send({ error: "Fail to create a category" });
    }
  })
  .post("/many", async (req, res) => {
    try {
      // const categories = await Category.insertMany(array);
      // const category = await Category.create({
      //   ...req.body,
      //   createdBy: req?.user?._id,
      // });

      array?.map(async (i) => {
        // let parent;

        await Category.create({ ...i, id: i.localId });
      });

      return res.status(200).json({ H: 1 });
    } catch (err) {
      console.log(err);
      res.status(500).send({ error: "Fail to create a category" });
    }
  })
  .put("/", async (req, res) => {
    const category = await Category.findByIdAndUpdate(
      { _id: req.category._id },
      { $set: req.body },
      { $upsert: true, new: true }
    ).select();
    res.status(200).json(category);
  })
  .put("/:id", async (req, res) => {
    const category = await Category.findByIdAndUpdate(req.params.id, req.body, {
      $upsert: true,
    });

    res.status(200).json(category);
  })
  .delete("/:id", async (req, res) => {
    await Category.deleteOne({ _id: req.params.id });
    res.status(200).json({ id: req.params.id });
  });

module.exports = route;
const array = [
  {
    localId: "1",
    name: "Women's & Girls' Fashion",
  },
  {
    localId: "2",
    name: "Health & Beauty",
  },
  {
    localId: "3",
    name: "Watches, Bags, Jewellery",
  },
  {
    localId: "4",
    name: "Men's & Boys' Fashion",
  },
  {
    localId: "5",
    name: "Babies & Toys",
  },
  {
    localId: "6",
    name: "Electronics Devices",
  },
  {
    localId: "7",
    name: "TV & Home Appliances",
  },
  {
    localId: "8",
    name: "Electronic Accessories",
  },
  {
    localId: "9",
    name: "Groceries & Pets",
  },
  {
    localId: "10",
    name: "Home & Lifestyle",
  },
  {
    localId: "11",
    name: "Sports & Outdoors",
  },
  {
    localId: "12",
    name: "Automotive & Motorbike",
  },
  {
    localId: "13",
    name: "Traditional Wear",
    slug: "womens-traditional-clothing",
    parentId: "1",
  },
  {
    localId: "14",
    name: "Shalwar Kameez",
    slug: "womens-shalwar-kameez",
    parentId: "13",
  },
  {
    localId: "15",
    name: "Sarees",
    slug: "womens-sarees",
    parentId: "13",
  },
  {
    localId: "16",
    name: "Kurtis",
    slug: "womens-kurtis",
    parentId: "13",
  },
  {
    localId: "17",
    name: "Unstitched Fabric",
    slug: "womens-lawn",
    parentId: "13",
  },
  {
    localId: "18",
    name: "Party Kameez & Gowns",
    slug: "womens-party-wear",
    parentId: "13",
  },
  {
    localId: "19",
    name: "Palazzo Pants & Culottes",
    slug: "womens-palazzo-pants-culottes",
    parentId: "13",
  },
  {
    localId: "20",
    name: "Pants, Palazzos & Capris",
    slug: "womens-palazzo",
    parentId: "13",
  },
  {
    localId: "21",
    name: "Muslim Wear",
    slug: "womens-abayas-and-hijabs",
    parentId: "1",
  },
  {
    localId: "22",
    name: "Abayas & Long Dresses",
    slug: "outerwear",
    parentId: "21",
  },
  {
    localId: "23",
    name: "Hijabs",
    slug: "womens-hijabs",
    parentId: "21",
  },
  {
    localId: "24",
    name: "Brooches",
    slug: "womens-brooches",
    parentId: "21",
  },
  {
    localId: "25",
    name: "Western Wear",
    slug: "womens-clothing",
    parentId: "1",
  },
  {
    localId: "26",
    name: "Dresses",
    slug: "womens-dresses",
    parentId: "25",
  },
  {
    localId: "27",
    name: "Tunics",
    slug: "tops-tunics",
    parentId: "25",
  },
  {
    localId: "28",
    name: "T-Shirts",
    slug: "womens-t-shirts",
    parentId: "25",
  },
  {
    localId: "29",
    name: "Tops",
    slug: "tops",
    parentId: "25",
  },
  {
    localId: "30",
    name: "Skirts",
    slug: "womens-skirts",
    parentId: "25",
  },
  {
    localId: "31",
    name: "Innerwear",
    slug: "womens-lingerie-sleepwear",
    parentId: "1",
  },
  {
    localId: "32",
    name: "Bras",
    slug: "womens-bras",
    parentId: "31",
  },
  {
    localId: "33",
    name: "Lingerie Sets",
    slug: "womens-lingerie",
    parentId: "31",
  },
  {
    localId: "34",
    name: "Panties",
    slug: "womens-panties",
    parentId: "31",
  },
  {
    localId: "35",
    name: "Robes & Bodysuits",
    slug: "robes-and-bodysuits",
    parentId: "31",
  },
  {
    localId: "36",
    name: "Sleep & Loungewear",
    slug: "sleepwear",
    parentId: "31",
  },
  {
    localId: "37",
    name: "Tank Tops",
    slug: "tank-tops-and-slips",
    parentId: "31",
  },
  {
    localId: "38",
    name: "Shapewear",
    slug: "womens-shapewear",
    parentId: "31",
  },
  {
    localId: "39",
    name: "Shoes",
    slug: "womens-shoes",
    parentId: "1",
  },
  {
    localId: "40",
    name: "Heels",
    slug: "shop-heeled-sandals",
    parentId: "39",
  },
  {
    localId: "41",
    name: "Flats",
    slug: "womens-ballet-flats",
    parentId: "39",
  },
  {
    localId: "42",
    name: "Sneakers",
    slug: "womens-sneakers",
    parentId: "39",
  },
  {
    localId: "43",
    name: "Pump Shoes",
    slug: "womens-pumps-heels",
    parentId: "39",
  },
  {
    localId: "44",
    name: "Bags",
    slug: "womens-bags",
    parentId: "1",
  },
  {
    localId: "45",
    name: "Crossbody & Shoulder Bags",
    slug: "women-crossbody-bag",
    parentId: "44",
  },
  {
    localId: "46",
    name: "Backpacks",
    slug: "womens-backpacks",
    parentId: "44",
  },
  {
    localId: "47",
    name: "Wallets",
    slug: "womens-wallets",
    parentId: "44",
  },
  {
    localId: "48",
    name: "Top Handle Bags",
    slug: "womens-office-digital",
    parentId: "44",
  },
  {
    localId: "49",
    name: "Watches",
    slug: "womens-watches",
    parentId: "1",
  },
  {
    localId: "50",
    name: "Casual",
    slug: "womens-fashion-watches-wsj",
    parentId: "49",
  },
  {
    localId: "51",
    name: "Fashion",
    slug: "womens-casual-watches-wsj",
    parentId: "49",
  },
  {
    localId: "52",
    name: "Business",
    slug: "womens-business-watches-wsj",
    parentId: "49",
  },
  {
    localId: "53",
    name: "Sports",
    slug: "womens-sports-watches-wsj",
    parentId: "49",
  },
  {
    localId: "54",
    name: "Accessories",
    slug: "womens-watch-accessories",
    parentId: "49",
  },
  {
    localId: "55",
    name: "Skin Care",
    slug: "skincare-beauty",
    parentId: "2",
  },
  {
    localId: "56",
    name: "Face Mask & Packs",
    slug: "facial-masks-peels",
    parentId: "55",
  },
  {
    localId: "57",
    name: "Face Wash & Cleansers",
    slug: "face-wash",
    parentId: "55",
  },
  {
    localId: "58",
    name: "Toner & Mists",
    slug: "toners",
    parentId: "55",
  },
  {
    localId: "59",
    name: "Serum & Essence",
    slug: "serums-creams",
    parentId: "55",
  },
  {
    localId: "60",
    name: "Moisturizers and Cream",
    slug: "skin-care-moisturizers-cream",
    parentId: "55",
  },
  {
    localId: "61",
    name: "Sunscreen and Aftersun",
    slug: "sun-care",
    parentId: "55",
  },
  {
    localId: "62",
    name: "Lip Balm and Treatment",
    slug: "lip-balms-treatments",
    parentId: "55",
  },
  {
    localId: "63",
    name: "Night Cream",
    slug: "night-creams",
    parentId: "55",
  },
  {
    localId: "64",
    name: "Laikou",
    slug: "laikou-brand",
    parentId: "55",
  },
  {
    localId: "65",
    name: "Bioaqua",
    slug: "bioaqua",
    parentId: "55",
  },
  {
    localId: "66",
    name: "Mamaearth",
    slug: "mamaearth-123544036",
    parentId: "55",
  },
  {
    localId: "67",
    name: "Simple",
    slug: "simple",
    parentId: "55",
  },
  {
    localId: "68",
    name: "Hair Care",
    slug: "hair-care-beauty",
    parentId: "2",
  },
  {
    localId: "69",
    name: "Hair Oils",
    slug: "hair-oils",
    parentId: "68",
  },
  {
    localId: "70",
    name: "Hair Treatments",
    slug: "treatments",
    parentId: "68",
  },
  {
    localId: "71",
    name: "Hair Coloring",
    slug: "hair-color",
    parentId: "68",
  },
  {
    localId: "72",
    name: "Shampoo",
    slug: "hair-shampoo",
    parentId: "68",
  },
  {
    localId: "73",
    name: "Conditioner",
    slug: "hair-conditioner",
    parentId: "68",
  },
  {
    localId: "74",
    name: "Hair Care Accessories",
    slug: "shop-hair-brushes",
    parentId: "68",
  },
  {
    localId: "75",
    name: "Wow Skin Science",
    slug: "wow-skin-science-121086437",
    parentId: "68",
  },
  {
    localId: "76",
    name: "Sunsilk",
    slug: "sunsilk",
    parentId: "68",
  },
  {
    localId: "77",
    name: "Ribana",
    slug: "ribana",
    parentId: "68",
  },
  {
    localId: "78",
    name: "Parachute",
    slug: "parachute-naturale",
    parentId: "68",
  },
  {
    localId: "79",
    name: "Tresemme",
    slug: "tresemme",
    parentId: "68",
  },
  {
    localId: "80",
    name: "Dove",
    slug: "dove",
    parentId: "68",
  },
  {
    localId: "81",
    name: "Makeup",
    slug: "womens-make-up",
    parentId: "2",
  },
  {
    localId: "82",
    name: "Face",
    slug: "face-makeup",
    parentId: "81",
  },
  {
    localId: "83",
    name: "Eyes",
    slug: "eye-makeup",
    parentId: "81",
  },
  {
    localId: "84",
    name: "Lips",
    slug: "lips",
    parentId: "81",
  },
  {
    localId: "85",
    name: "Nails",
    slug: "nails-makeup",
    parentId: "81",
  },
  {
    localId: "86",
    name: "Makeup Palettes & Sets",
    slug: "makeup-kits-palettes",
    parentId: "81",
  },
  {
    localId: "87",
    name: "Makeup Accessories",
    slug: "makeup-accessories",
    parentId: "81",
  },
  {
    localId: "88",
    name: "Makeup Removers",
    slug: "womens-make-up-remover",
    parentId: "81",
  },
  {
    localId: "89",
    name: "M.A.C",
    slug: "m-a-c-two",
    parentId: "81",
  },
  {
    localId: "90",
    name: "Maybelline",
    slug: "maybelline",
    parentId: "81",
  },
  {
    localId: "91",
    name: "Makeup Revolution",
    slug: "makeup-revolution",
    parentId: "81",
  },
  {
    localId: "92",
    name: "Fenty Beauty",
    slug: "fenty-beauty-1-137252",
    parentId: "81",
  },
  {
    localId: "93",
    name: "Morphe",
    slug: "morphe",
    parentId: "81",
  },
  {
    localId: "94",
    name: "Fragrances",
    slug: "fragrances",
    parentId: "2",
  },
  {
    localId: "95",
    name: "Women's Perfume",
    slug: "women-fragrance",
    parentId: "94",
  },
  {
    localId: "96",
    name: "Women's Body Spray",
    slug: "womens-body-spray",
    parentId: "94",
  },
  {
    localId: "97",
    name: "Roll-on & Deo",
    slug: "deodorants",
    parentId: "94",
  },
  {
    localId: "98",
    name: "Men's Perfume",
    slug: "men-fragrance",
    parentId: "94",
  },
  {
    localId: "99",
    name: "Men's Body Spray",
    slug: "men-fragrance",
    parentId: "94",
  },
  {
    localId: "100",
    name: "Attar",
    slug: "fragrance-attar",
    parentId: "94",
  },
  {
    localId: "101",
    name: "My Perfumes",
    slug: "my-perfumes",
    parentId: "94",
  },
  {
    localId: "102",
    name: "Al Haramain",
    slug: "al-haramain-perfumes",
    parentId: "94",
  },
  {
    localId: "103",
    name: "Aris",
    slug: "aris-124581432",
    parentId: "94",
  },
  {
    localId: "104",
    name: "Hugo Boss",
    slug: "hugo-boss",
    parentId: "94",
  },
  {
    localId: "105",
    name: "Calvin Klein",
    slug: "calvin-klein",
    parentId: "94",
  },
  {
    localId: "106",
    name: "Versace",
    slug: "versace",
    parentId: "94",
  },
  {
    localId: "107",
    name: "Beauty Tools",
    slug: "health-beauty-tools",
    parentId: "2",
  },
  {
    localId: "108",
    name: "Skin Care Tools",
    slug: "hb-skin-care-tools",
    parentId: "99",
  },
  {
    localId: "109",
    name: "Hair Styling Appliances",
    slug: "hair-styling-appliances",
    parentId: "99",
  },
  {
    localId: "110",
    name: "Electric Massagers",
    slug: "massage-relaxation",
    parentId: "99",
  },
  {
    localId: "111",
    name: "Hair Removal Accessories",
    slug: "hb-hair-removal-accessories",
    parentId: "99",
  },
  {
    localId: "112",
    name: "Eyelash Extension Tools",
    slug: "eyelash-cslugers",
    parentId: "99",
  },
  {
    localId: "113",
    name: "Nail Extension Tools",
    slug: "artificial-nails",
    parentId: "99",
  },
  {
    localId: "114",
    name: "Foot Care",
    slug: "foot-relief",
    parentId: "99",
  },
  {
    localId: "115",
    name: "Kemei",
    slug: "kemei",
    parentId: "99",
  },
  {
    localId: "116",
    name: "Philips",
    slug: "philips-brand",
    parentId: "99",
  },
  {
    localId: "117",
    name: "Panasonic",
    slug: "hair-styling-appliances",
    parentId: "99",
  },
  {
    localId: "118",
    name: "Nova",
    slug: "hair-styling-appliances",
    parentId: "99",
  },
  {
    localId: "119",
    name: "Venus",
    slug: "health-beauty-tools",
    parentId: "99",
  },
  {
    localId: "120",
    name: "Bath & Body",
    slug: "bath-body",
    parentId: "2",
  },
  {
    localId: "121",
    name: "Body & Massage Oils",
    slug: "body-oils",
    parentId: "120",
  },
  {
    localId: "122",
    name: "Body Scrubs",
    slug: "body-wash-scrubs",
    parentId: "120",
  },
  {
    localId: "123",
    name: "Soaps & Body Wash",
    slug: "soaps-wash",
    parentId: "120",
  },
  {
    localId: "124",
    name: "Hair Removal",
    slug: "hair-removal-tools",
    parentId: "120",
  },
  {
    localId: "125",
    name: "Talcum Powder",
    slug: "womans-hygiene-talcum-powder",
    parentId: "120",
  },
  {
    localId: "126",
    name: "Hand Care",
    slug: "hand-care",
    parentId: "120",
  },
  {
    localId: "127",
    name: "Bath & Body Accessories",
    slug: "bath-body-accessories",
    parentId: "120",
  },
  {
    localId: "128",
    name: "Dettol",
    slug: "soaps-wash",
    parentId: "120",
  },
  {
    localId: "129",
    name: "The Body Shop",
    slug: "the-body-shop",
    parentId: "120",
  },
  {
    localId: "130",
    name: "Godrej NO 1",
    slug: "godrej-no-1-124002483",
    parentId: "120",
  },
  {
    localId: "131",
    name: "Lux",
    slug: "lux",
    parentId: "120",
  },
  {
    localId: "132",
    name: "Mollywaiz",
    slug: "mollywaiz",
    parentId: "120",
  },
  {
    localId: "133",
    name: "Personal Care",
    slug: "personal-care",
    parentId: "2",
  },
  {
    localId: "134",
    name: "Toothpaste",
    slug: "toothpaste",
    parentId: "133",
  },
  {
    localId: "135",
    name: "Toothbrush",
    slug: "toothbrushes",
    parentId: "133",
  },
  {
    localId: "136",
    name: "Electric Toothbrush",
    slug: "electric-toothbrushes",
    parentId: "133",
  },
  {
    localId: "137",
    name: "Dental Floss",
    slug: "dental-flosses-sticks",
    parentId: "133",
  },
  {
    localId: "138",
    name: "Mouthwash",
    slug: "mouth_freshener",
    parentId: "133",
  },
  {
    localId: "139",
    name: "Teeth Whitening",
    slug: "teeth-whitening",
    parentId: "133",
  },
  {
    localId: "140",
    name: "Sanitary Napkins",
    slug: "hb-sanitary-napkins",
    parentId: "133",
  },
  {
    localId: "141",
    name: "Ear Care",
    slug: "ear-care",
    parentId: "133",
  },
  {
    localId: "142",
    name: "Contact Lens",
    slug: "eyecare-contact-lenses",
    parentId: "133",
  },
  {
    localId: "143",
    name: "Freedom",
    slug: "freedom",
    parentId: "133",
  },
  {
    localId: "144",
    name: "Senora",
    slug: "senora",
    parentId: "133",
  },
  {
    localId: "145",
    name: "Whisper",
    slug: "whisper",
    parentId: "133",
  },
  {
    localId: "146",
    name: "Men's Care",
    slug: "mens-grooming",
    parentId: "2",
  },
  {
    localId: "147",
    name: "Shaving & Grooming",
    slug: "mens-shaving-grooming",
    parentId: "146",
  },
  {
    localId: "148",
    name: "Body and Skin Care",
    slug: "men-skin-care",
    parentId: "146",
  },
  {
    localId: "149",
    name: "Hair Care",
    slug: "men-hair-care",
    parentId: "146",
  },
  {
    localId: "150",
    name: "Aftershave & Foam",
    slug: "shaving-accessories",
    parentId: "146",
  },
  {
    localId: "151",
    name: "Men's Perfume",
    slug: "men-fragrance",
    parentId: "146",
  },
  {
    localId: "152",
    name: "Men's Body Spray",
    slug: "men-fragrance",
    parentId: "146",
  },
  {
    localId: "153",
    name: "Sports Nutrition",
    slug: "sports-nutrition",
    parentId: "146",
  },
  {
    localId: "154",
    name: "Beardo",
    slug: "beardo",
    parentId: "146",
  },
  {
    localId: "155",
    name: "Nivea",
    slug: "nivea",
    parentId: "146",
  },
  {
    localId: "156",
    name: "Gillette",
    slug: "gillette",
    parentId: "146",
  },
  {
    localId: "157",
    name: "Muuchstac",
    slug: "muuchstac-121159469",
    parentId: "146",
  },
  {
    localId: "158",
    name: "Urban Gabru",
    slug: "urbangabru-124177864",
    parentId: "146",
  },
  {
    localId: "159",
    name: "Sexual Wellness",
    slug: "sexual-wellness",
    parentId: "2",
  },
  {
    localId: "160",
    name: "Condoms",
    slug: "shop-condoms",
    parentId: "159",
  },
  {
    localId: "161",
    name: "Lubricants",
    slug: "lubricants-sexual-health",
    parentId: "159",
  },
  {
    localId: "162",
    name: "Durex",
    slug: "durex",
    parentId: "159",
  },
  {
    localId: "163",
    name: "Coral",
    slug: "coral",
    parentId: "159",
  },
  {
    localId: "164",
    name: "Sensation",
    slug: "sensation",
    parentId: "159",
  },
  {
    localId: "165",
    name: "Manforce",
    slug: "manforce",
    parentId: "159",
  },
  {
    localId: "166",
    name: "Grip Unlimited",
    slug: "grip-unlimited",
    parentId: "159",
  },
  {
    localId: "167",
    name: "Panther",
    slug: "panther",
    parentId: "159",
  },
  {
    localId: "168",
    name: "Skore",
    slug: "skore",
    parentId: "159",
  },
  {
    localId: "169",
    name: "Nottyboy",
    slug: "nottyboy-123708690",
    parentId: "159",
  },
  {
    localId: "170",
    name: "Kamasutra",
    slug: "kamasutra",
    parentId: "159",
  },
  {
    localId: "171",
    name: "Romantic",
    slug: "romantic",
    parentId: "159",
  },
  {
    localId: "172",
    name: "Kids Bags",
    slug: "school-bags",
    parentId: "3",
  },
  {
    localId: "173",
    name: "Backpacks",
    slug: "kids-backpacks",
    parentId: "172",
  },
  {
    localId: "174",
    name: "Bags",
    slug: "kids-shoulder-bags",
    parentId: "172",
  },
  {
    localId: "175",
    name: "School Bags & Backpack",
    slug: "school-bags-backpack",
    parentId: "172",
  },
  {
    localId: "176",
    name: "Laptop Bags & Cases",
    slug: "laptop-bag",
    parentId: "3",
  },
  {
    localId: "177",
    name: "Backpacks",
    slug: "laptop-bags-backpacks",
    parentId: "176",
  },
  {
    localId: "178",
    name: "Briefcases",
    slug: "laptop-bags-briefcases",
    parentId: "176",
  },
  {
    localId: "179",
    name: "Laptop cases",
    slug: "laptop-bag-case",
    parentId: "176",
  },
  {
    localId: "180",
    name: "Shoulder & Messenger Bags",
    slug: "laptop-bags-shoulder-messenger-bags",
    parentId: "176",
  },
  {
    localId: "181",
    name: "Luggage",
    slug: "bags-luggage",
    parentId: "3",
  },
  {
    localId: "182",
    name: "Carry-Ons",
    slug: "bags-luggage-carryons",
    parentId: "181",
  },
  {
    localId: "183",
    name: "Kids Luggage",
    slug: "bags-luggage-kids-luggage",
    parentId: "181",
  },
  {
    localId: "184",
    name: "Luggage Sets",
    slug: "bags-luggage-luggage-sets",
    parentId: "181",
  },
  {
    localId: "185",
    name: "Suitcases",
    slug: "bags-luggage-suitcases",
    parentId: "181",
  },
  {
    localId: "186",
    name: "Travel Duffels",
    slug: "luggage-travel-duffels",
    parentId: "181",
  },
  {
    localId: "187",
    name: "Travel Bags",
    slug: "travels",
    parentId: "3",
  },
  {
    localId: "188",
    name: "Waist Packs",
    slug: "waist-packs",
    parentId: "187",
  },
  {
    localId: "189",
    name: "Men's Bags",
    slug: "mens-bags",
    parentId: "3",
  },
  {
    localId: "190",
    name: "Backpacks",
    slug: "mens-fashion-backpacks",
    parentId: "189",
  },
  {
    localId: "191",
    name: "Business Bags",
    slug: "backpacks-and-briefcases",
    parentId: "189",
  },
  {
    localId: "192",
    name: "Crossbody Bags",
    slug: "men-crossbody-bag",
    parentId: "189",
  },
  {
    localId: "193",
    name: "Messenger Bags",
    slug: "men-messenger-bags",
    parentId: "189",
  },
  {
    localId: "194",
    name: "Tote Bags",
    slug: "mens-tote-bags",
    parentId: "189",
  },
  {
    localId: "195",
    name: "Wallets & Accessories",
    slug: "mens-wallets-cardholders",
    parentId: "189",
  },
  {
    localId: "196",
    name: "Women's Bags",
    slug: "womens-bags",
    parentId: "3",
  },
  {
    localId: "197",
    name: "Backpacks",
    slug: "womens-backpacks",
    parentId: "196",
  },
  {
    localId: "198",
    name: "Cross Body & Shoulder Bags",
    slug: "women-crossbody-bag",
    parentId: "196",
  },
  {
    localId: "199",
    name: "Bag Charms & Accessories",
    slug: "womens-bag-charms",
    parentId: "196",
  },
  {
    localId: "200",
    name: "Clutches",
    slug: "womens-clutch-bags",
    parentId: "196",
  },
  {
    localId: "201",
    name: "Top-Handle Bags",
    slug: "womens-office-digital",
    parentId: "196",
  },
  {
    localId: "202",
    name: "Tote Bags",
    slug: "tote-bags",
    parentId: "196",
  },
  {
    localId: "203",
    name: "Wallets",
    slug: "womens-wallets",
    parentId: "196",
  },
  {
    localId: "204",
    name: "Wristlets",
    slug: "bags-wristlets",
    parentId: "196",
  },
  {
    localId: "205",
    name: "Men's Watches",
    slug: "mens-watches",
    parentId: "3",
  },
  {
    localId: "206",
    name: "Business",
    slug: "mens-analog",
    parentId: "205",
  },
  {
    localId: "207",
    name: "Casual",
    slug: "mens-digital",
    parentId: "205",
  },
  {
    localId: "208",
    name: "Fashion",
    slug: "mens-chronograph",
    parentId: "205",
  },
  {
    localId: "209",
    name: "Sports",
    slug: "mens-sports-watches",
    parentId: "205",
  },
  {
    localId: "210",
    name: "Accessories",
    slug: "mens-watch-accessories",
    parentId: "205",
  },
  {
    localId: "211",
    name: "Women's Watches",
    slug: "womens-watches",
    parentId: "3",
  },
  {
    localId: "212",
    name: "Fashion",
    slug: "womens-fashion-watches-wsj",
    parentId: "211",
  },
  {
    localId: "213",
    name: "Casual",
    slug: "womens-casual-watches-wsj",
    parentId: "211",
  },
  {
    localId: "214",
    name: "Business",
    slug: "womens-business-watches-wsj",
    parentId: "211",
  },
  {
    localId: "215",
    name: "Sports",
    slug: "womens-sports-watches-wsj",
    parentId: "211",
  },
  {
    localId: "216",
    name: "Accessories",
    slug: "womens-watch-accessories",
    parentId: "211",
  },
  {
    localId: "217",
    name: "Kids Watches",
    slug: "kids-watches-wsj",
    parentId: "3",
  },
  {
    localId: "218",
    name: "Boys",
    slug: "boys-watches",
    parentId: "217",
  },
  {
    localId: "219",
    name: "Girls",
    slug: "girls-watches",
    parentId: "217",
  },
  {
    localId: "220",
    name: "Women's Jewellery",
    slug: "shop-womens-jewellery",
    parentId: "3",
  },
  {
    localId: "221",
    name: "Nose Pin & Body Piercings",
    slug: "womens-body-piercings",
    parentId: "220",
  },
  {
    localId: "222",
    name: "Bracelets",
    slug: "womens-bangles-bracelets",
    parentId: "220",
  },
  {
    localId: "223",
    name: "Necklaces",
    slug: "womens-necklaces-chains",
    parentId: "220",
  },
  {
    localId: "224",
    name: "Earrings",
    slug: "fashion-womens-earrings",
    parentId: "220",
  },
  {
    localId: "225",
    name: "Rings",
    slug: "womens-rings",
    parentId: "220",
  },
  {
    localId: "226",
    name: "Jewellery Storage",
    slug: "womens-jewellery-storage",
    parentId: "220",
  },
  {
    localId: "227",
    name: "Men's Jewellery",
    slug: "mens-jewellery",
    parentId: "3",
  },
  {
    localId: "228",
    name: "Bracelets",
    slug: "shop-mens-bracelets",
    parentId: "227",
  },
  {
    localId: "229",
    name: "Earrings",
    slug: "mens-earings",
    parentId: "227",
  },
  {
    localId: "230",
    name: "Necklaces",
    slug: "mens-necklaces",
    parentId: "227",
  },
  {
    localId: "231",
    name: "Pendants",
    slug: "mens-pendants",
    parentId: "227",
  },
  {
    localId: "232",
    name: "Rings",
    slug: "shop-mens-rings",
    parentId: "227",
  },
  {
    localId: "233",
    name: "Tie clips",
    slug: "tie-clips",
    parentId: "227",
  },
  {
    localId: "234",
    name: "SunglassesMen's SunglassesWomen's Sunglasses",
    slug: "sunglasses",
    parentId: "3",
  },
  {
    localId: "235",
    name: "Men's Sunglasses",
    slug: "mens-sunglasses",
    parentId: "234",
  },
  {
    localId: "236",
    name: "Women's Sunglasses",
    slug: "womens-sunglasses",
    parentId: "234",
  },
  {
    localId: "237",
    name: "Clothing",
    slug: "mens-clothing",
    parentId: "4",
  },
  {
    localId: "238",
    name: "T-Shirts",
    slug: "mens-t-shirts",
    parentId: "237",
  },
  {
    localId: "239",
    name: "Jeans",
    slug: "mens-jeans",
    parentId: "237",
  },
  {
    localId: "240",
    name: "Casual Shirts",
    slug: "mens-casual-shirts",
    parentId: "237",
  },
  {
    localId: "241",
    name: "Kurtas",
    slug: "mens-kurtas",
    parentId: "237",
  },
  {
    localId: "242",
    name: "Polo Shirts",
    slug: "mens-polo-shirts",
    parentId: "237",
  },
  {
    localId: "243",
    name: "Socks",
    slug: "mens-socks",
    parentId: "237",
  },
  {
    localId: "244",
    name: "Rain Coats & Trenches",
    slug: "men-rain-coats",
    parentId: "237",
  },
  {
    localId: "245",
    name: "Joggers & Sweats",
    slug: "mens-sweat-pants",
    parentId: "237",
  },
  {
    localId: "246",
    name: "Chinos",
    slug: "mens-khakis-chinos",
    parentId: "237",
  },
  {
    localId: "247",
    name: "Trunks & Boxers",
    slug: "mens-boxers",
    parentId: "237",
  },
  {
    localId: "248",
    name: "Shoes",
    slug: "mens-shoes",
    parentId: "4",
  },
  {
    localId: "249",
    name: "Sneakers",
    slug: "mens-sneakers",
    parentId: "248",
  },
  {
    localId: "250",
    name: "Slip-Ons & Loafers",
    slug: "mens-slip-ons",
    parentId: "248",
  },
  {
    localId: "251",
    name: "Flip Flops",
    slug: "mens-flip-flops",
    parentId: "248",
  },
  {
    localId: "252",
    name: "Formal Shoes",
    slug: "mens-formal-shoes",
    parentId: "248",
  },
  {
    localId: "253",
    name: "Sandals",
    slug: "mens-sandal",
    parentId: "248",
  },
  {
    localId: "254",
    name: "Rain Boots",
    slug: "mens-wellies",
    parentId: "248",
  },
  {
    localId: "255",
    name: "Shoes Accessories",
    slug: "mens-shoe-care",
    parentId: "248",
  },
  {
    localId: "256",
    name: "Muslim Wear",
    slug: "men-muslim-wear",
    parentId: "4",
  },
  {
    localId: "257",
    name: "Batik Shirts",
    slug: "men-muslim-batik-shirts",
    parentId: "256",
  },
  {
    localId: "258",
    name: "Jubbahs",
    slug: "mens-ahrams",
    parentId: "256",
  },
  {
    localId: "259",
    name: "Muslimin Shirts",
    slug: "men-muslimin-shirts",
    parentId: "256",
  },
  {
    localId: "260",
    name: "Accessories",
    slug: "men-muslim-accessories",
    parentId: "256",
  },
  {
    localId: "261",
    name: "Accessories",
    slug: "men-accessories",
    parentId: "4",
  },
  {
    localId: "262",
    name: "Belts",
    slug: "mens-belts",
    parentId: "261",
  },
  {
    localId: "263",
    name: "Bow Ties",
    slug: "mens-tie-cases",
    parentId: "261",
  },
  {
    localId: "264",
    name: "Cufflinks",
    slug: "mens-cufflinks",
    parentId: "261",
  },
  {
    localId: "265",
    name: "Hats & Caps",
    slug: "men-accessories-hats",
    parentId: "261",
  },
  {
    localId: "266",
    name: "Ties",
    slug: "mens-ties",
    parentId: "261",
  },
  {
    localId: "267",
    name: "Umbrellas",
    slug: "fashion-umbrellas",
    parentId: "261",
  },
  {
    localId: "268",
    name: "Bags",
    slug: "mens-bags",
    parentId: "4",
  },
  {
    localId: "269",
    name: "Backpacks",
    slug: "mens-fashion-backpacks",
    parentId: "268",
  },
  {
    localId: "270",
    name: "Business Bags",
    slug: "backpacks-and-briefcases",
    parentId: "268",
  },
  {
    localId: "271",
    name: "Crossbody Bags",
    slug: "men-crossbody-bag",
    parentId: "268",
  },
  {
    localId: "272",
    name: "Messenger Bags",
    slug: "men-messenger-bags",
    parentId: "268",
  },
  {
    localId: "273",
    name: "Tote Bags",
    slug: "mens-tote-bags",
    parentId: "268",
  },
  {
    localId: "274",
    name: "Wallets & Accessories",
    slug: "mens-sports-wallets",
    parentId: "268",
  },
  {
    localId: "275",
    name: "Watches",
    slug: "mens-watches",
    parentId: "4",
  },
  {
    localId: "276",
    name: "Business",
    slug: "mens-analog",
    parentId: "275",
  },
  {
    localId: "277",
    name: "Casual",
    slug: "mens-digital",
    parentId: "275",
  },
  {
    localId: "278",
    name: "Fashion",
    slug: "mens-chronograph",
    parentId: "275",
  },
  {
    localId: "279",
    name: "Sports",
    slug: "mens-sports-watches",
    parentId: "275",
  },
  {
    localId: "280",
    name: "Accessories",
    slug: "mens-watch-accessories",
    parentId: "275",
  },
  {
    localId: "281",
    name: "Eyewear",
    slug: "eyewear-mens",
    parentId: "4",
  },
  {
    localId: "282",
    name: "Eyeglasses",
    slug: "mens-eyeglasses",
    parentId: "281",
  },
  {
    localId: "283",
    name: "Sunglasses",
    slug: "mens-sunglasses",
    parentId: "281",
  },
  {
    localId: "284",
    name: "Jewellery",
    slug: "mens-jewellery",
    parentId: "4",
  },
  {
    localId: "285",
    name: "Bracelets",
    slug: "shop-mens-bracelets",
    parentId: "284",
  },
  {
    localId: "286",
    name: "Earrings",
    slug: "mens-earings",
    parentId: "284",
  },
  {
    localId: "287",
    name: "Necklaces",
    slug: "mens-necklaces",
    parentId: "284",
  },
  {
    localId: "288",
    name: "Pendants",
    slug: "mens-pendants",
    parentId: "284",
  },
  {
    localId: "289",
    name: "Rings",
    slug: "shop-mens-rings",
    parentId: "284",
  },
  {
    localId: "290",
    name: "Tie clips",
    slug: "tie-clips",
    parentId: "284",
  },
  {
    localId: "291",
    name: "Latest in Men's Fashion",
    slug: "catalog",
    parentId: "4",
  },
  {
    localId: "292",
    name: "Hats & Caps",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "293",
    name: "Joggers & Sweats",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "294",
    name: "Men's Belts",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "295",
    name: "Polo Shirts",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "296",
    name: "Men's Kurtas",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "297",
    name: "Slip-Ons & Loafers",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "298",
    name: "Men's Jeans",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "299",
    name: "Men's Watches",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "300",
    name: "Sunglasses",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "301",
    name: "T-Shirts",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "302",
    name: "Hoodies & Sweatshirts",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "303",
    name: "Sneakers",
    slug: "catalog",
    parentId: "291",
  },
  {
    localId: "304",
    name: "Diapering & Potty",
    slug: "baby-toddler-diapers-potties",
    parentId: "5",
  },
  {
    localId: "305",
    name: "Diapers",
    slug: "baby-diapers",
    parentId: "304",
  },
  {
    localId: "306",
    name: "Cloth Diapers",
    slug: "cloth-diapers-and-accessories",
    parentId: "304",
  },
  {
    localId: "307",
    name: "Diaper Bags",
    slug: "diaper-bags",
    parentId: "304",
  },
  {
    localId: "308",
    name: "Potty Chair & Seat",
    slug: "potty-training",
    parentId: "304",
  },
  {
    localId: "309",
    name: "Wipes",
    slug: "wipes-holders",
    parentId: "304",
  },
  {
    localId: "310",
    name: "Huggies",
    slug: "shop",
    parentId: "304",
  },
  {
    localId: "311",
    name: "Molfix",
    slug: "shop",
    parentId: "304",
  },
  {
    localId: "312",
    name: "Twinkle",
    slug: "shop",
    parentId: "304",
  },
  {
    localId: "313",
    name: "Avonee",
    slug: "shop",
    parentId: "304",
  },
  {
    localId: "314",
    name: "Smile",
    slug: "baby-diapers",
    parentId: "304",
  },
  {
    localId: "315",
    name: "Neocare",
    slug: "shop",
    parentId: "304",
  },
  {
    localId: "316",
    name: "Happy Nappy",
    slug: "happy-nappy-124040458",
    parentId: "304",
  },
  {
    localId: "317",
    name: "Feeding",
    slug: "feeding",
    parentId: "5",
  },
  {
    localId: "318",
    name: "Baby & Toddler Foods",
    slug: "baby-n-toddler-food",
    parentId: "317",
  },
  {
    localId: "319",
    name: "Bottle Feeding",
    slug: "baby-toddler-bottles",
    parentId: "317",
  },
  {
    localId: "320",
    name: "Breastfeeding",
    slug: "breast-feeding",
    parentId: "317",
  },
  {
    localId: "321",
    name: "Feeding Chairs & Seats",
    slug: "high-chairs",
    parentId: "317",
  },
  {
    localId: "322",
    name: "Milk Formula",
    slug: "formula-milk",
    parentId: "317",
  },
  {
    localId: "323",
    name: "Feeding Bowls, Cups & Bibs",
    slug: "baby-utensils",
    parentId: "317",
  },
  {
    localId: "324",
    name: "Pacifiers",
    slug: "pacifiers-and-accessories",
    parentId: "317",
  },
  {
    localId: "325",
    name: "Cerelac",
    slug: "cerelac-2",
    parentId: "317",
  },
  {
    localId: "326",
    name: "Lactogen",
    slug: "lactogen-2",
    parentId: "317",
  },
  {
    localId: "327",
    name: "Nan",
    slug: "nan",
    parentId: "317",
  },
  {
    localId: "328",
    name: "Heinz",
    slug: "baby-food-snacks",
    parentId: "317",
  },
  {
    localId: "329",
    name: "Aptamil",
    slug: "aptamil",
    parentId: "317",
  },
  {
    localId: "330",
    name: "Baby Personal Care",
    slug: "baby-personal-care",
    parentId: "5",
  },
  {
    localId: "331",
    name: "Baby Detergent",
    slug: "baby-detergent",
    parentId: "330",
  },
  {
    localId: "332",
    name: "Bathing Tubs & Toys",
    slug: "bath-tubs-seats",
    parentId: "330",
  },
  {
    localId: "333",
    name: "Shampoo & Conditioners",
    slug: "baby-shampoo-conditioners",
    parentId: "330",
  },
  {
    localId: "334",
    name: "Lotions & Creams",
    slug: "lotions",
    parentId: "330",
  },
  {
    localId: "335",
    name: "Oils",
    slug: "oils",
    parentId: "330",
  },
  {
    localId: "336",
    name: "Powders",
    slug: "powder-skin-care",
    parentId: "330",
  },
  {
    localId: "337",
    name: "Soaps & Body Wash",
    slug: "baby-soaps-cleaners",
    parentId: "330",
  },
  {
    localId: "338",
    name: "Toothbrushes & Toothpaste",
    slug: "baby-oral-care",
    parentId: "330",
  },
  {
    localId: "339",
    name: "Washcloths & Towels",
    slug: "baby-towels",
    parentId: "330",
  },
  {
    localId: "340",
    name: "Kodomo",
    slug: "shop",
    parentId: "330",
  },
  {
    localId: "341",
    name: "Just For Baby",
    slug: "just-for-baby-196081",
    parentId: "330",
  },
  {
    localId: "342",
    name: "Bebble",
    slug: "shop",
    parentId: "330",
  },
  {
    localId: "343",
    name: "Baby Gear",
    slug: "baby-gear",
    parentId: "5",
  },
  {
    localId: "344",
    name: "Baby Soft Carriers",
    slug: "baby-toddler-carriers",
    parentId: "343",
  },
  {
    localId: "345",
    name: "Baby Car Seats",
    slug: "catalog",
    parentId: "343",
  },
  {
    localId: "346",
    name: "Kids Bags & Luggage",
    slug: "kids-bag-luggages",
    parentId: "343",
  },
  {
    localId: "347",
    name: "Playards & Playpens",
    slug: "baby-playards",
    parentId: "343",
  },
  {
    localId: "348",
    name: "Strollers & Prams",
    slug: "catalog",
    parentId: "343",
  },
  {
    localId: "349",
    name: "Bouncers & Jumpers",
    slug: "swings-jumpers-bouncers",
    parentId: "343",
  },
  {
    localId: "350",
    name: "Swings",
    slug: "baby-swings",
    parentId: "343",
  },
  {
    localId: "351",
    name: "Walkers",
    slug: "baby-toddler-walkers",
    parentId: "343",
  },
  {
    localId: "352",
    name: "Kids Paradise",
    slug: "shop",
    parentId: "343",
  },
  {
    localId: "353",
    name: "Toy House",
    slug: "shop",
    parentId: "343",
  },
  {
    localId: "354",
    name: "Wall Touch",
    slug: "shop",
    parentId: "343",
  },
  {
    localId: "355",
    name: "Kids World",
    slug: "shop",
    parentId: "343",
  },
  {
    localId: "356",
    name: "Nursery",
    slug: "baby-toddler-nursery",
    parentId: "5",
  },
  {
    localId: "357",
    name: "Cribs & Cradles",
    slug: "nursery-furniture-cradles",
    parentId: "356",
  },
  {
    localId: "358",
    name: "Furniture Sets",
    slug: "nursery-furniture-sets",
    parentId: "356",
  },
  {
    localId: "359",
    name: "Blankets & Wrappers",
    slug: "nursery-blankets",
    parentId: "356",
  },
  {
    localId: "360",
    name: "Baby Pillows & Protection",
    slug: "baby-pillows-protector-and-cases",
    parentId: "356",
  },
  {
    localId: "361",
    name: "Baby Bedding Sets",
    slug: "toddler-bedding-sets",
    parentId: "356",
  },
  {
    localId: "362",
    name: "Baby Quilts & Bed Covers",
    slug: "baby-quilts",
    parentId: "356",
  },
  {
    localId: "363",
    name: "Storage & Organization",
    slug: "nursery-storage-baskets",
    parentId: "356",
  },
  {
    localId: "364",
    name: "Tanzina Boutique's",
    slug: "baby-quilts",
    parentId: "356",
  },
  {
    localId: "365",
    name: "Livingtex",
    slug: "nursery-blankets",
    parentId: "356",
  },
  {
    localId: "366",
    name: "Wall Touch",
    slug: "baby-toddler-nursery",
    parentId: "356",
  },
  {
    localId: "367",
    name: "Frozen Bedroom Set",
    slug: "products",
    parentId: "356",
  },
  {
    localId: "368",
    name: "Princess Canopy Bed",
    slug: "products",
    parentId: "356",
  },
  {
    localId: "369",
    name: "Maternity Care",
    slug: "womens-maternity-care",
    parentId: "5",
  },
  {
    localId: "370",
    name: "Maternity Belts",
    slug: "maternity-supporting-belts",
    parentId: "369",
  },
  {
    localId: "371",
    name: "Maternity Tops & Intimates",
    slug: "maternity-care-wear",
    parentId: "369",
  },
  {
    localId: "372",
    name: "Moisturizers & Creams",
    slug: "baby-maternity-moisturizers-creams",
    parentId: "369",
  },
  {
    localId: "373",
    name: "Pregnancy Pillows",
    slug: "maternity-pregnancy-pillows",
    parentId: "369",
  },
  {
    localId: "374",
    name: "Palmer's",
    slug: "palmer-s",
    parentId: "369",
  },
  {
    localId: "375",
    name: "Zita Matenity Wear",
    slug: "zita-maternity-wear",
    parentId: "369",
  },
  {
    localId: "376",
    name: "Baby Care & Gifts",
    slug: "baby-health-care-grooming",
    parentId: "5",
  },
  {
    localId: "377",
    name: "Nasal Aspirators",
    slug: "baby-nasal-aspirators",
    parentId: "376",
  },
  {
    localId: "378",
    name: "Nail Care",
    slug: "baby-nail-care",
    parentId: "376",
  },
  {
    localId: "379",
    name: "Masks & Repellents",
    slug: "mask-repellents",
    parentId: "376",
  },
  {
    localId: "380",
    name: "Safety & Straps",
    slug: "cabinet-locks-straps",
    parentId: "376",
  },
  {
    localId: "381",
    name: "Electrical Safety",
    slug: "baby-electrical-safety",
    parentId: "376",
  },
  {
    localId: "382",
    name: "Baby Monitoring",
    slug: "baby-toddler-monitors",
    parentId: "376",
  },
  {
    localId: "383",
    name: "Albums, Frames & Journals",
    slug: "baby-albums-frames",
    parentId: "376",
  },
  {
    localId: "384",
    name: "Keepsakes",
    slug: "baby-keepsakes",
    parentId: "376",
  },
  {
    localId: "385",
    name: "Kids Toys",
    slug: "toys-games",
    parentId: "5",
  },
  {
    localId: "386",
    name: "Action Figures & Collectibles",
    slug: "toys-action-figures",
    parentId: "385",
  },
  {
    localId: "387",
    name: "Arts & Crafts for Kids",
    slug: "toys-arts-craft",
    parentId: "385",
  },
  {
    localId: "388",
    name: "Ball Prit & Accessories",
    slug: "ball-pits-and-accessories",
    parentId: "385",
  },
  {
    localId: "389",
    name: "Block & Building Toys",
    slug: "blocks-building-toys-games",
    parentId: "385",
  },
  {
    localId: "390",
    name: "Doll & Accessories",
    slug: "dolls-accessories",
    parentId: "385",
  },
  {
    localId: "391",
    name: "Dress Up & Pretend Play",
    slug: "kids-dress-up",
    parentId: "385",
  },
  {
    localId: "392",
    name: "Electronic toys",
    slug: "electronic-toys",
    parentId: "385",
  },
  {
    localId: "393",
    name: "Learning & Education",
    slug: "educational-toys-games",
    parentId: "385",
  },
  {
    localId: "394",
    name: "Party Supplies",
    slug: "party-supplies",
    parentId: "385",
  },
  {
    localId: "395",
    name: "Puzzle",
    slug: "toys-puzzles",
    parentId: "385",
  },
  {
    localId: "396",
    name: "Slime & Squishy Toys",
    slug: "slime-squishy-toys",
    parentId: "385",
  },
  {
    localId: "397",
    name: "Soft Toys",
    slug: "stuffed-animals-plush",
    parentId: "385",
  },
  {
    localId: "398",
    name: "Baby & Toddler Toys",
    slug: "baby-toddler-toys-games",
    parentId: "5",
  },
  {
    localId: "399",
    name: "Activity Gym & Playmats",
    slug: "activity-play-centers",
    parentId: "398",
  },
  {
    localId: "400",
    name: "Ball",
    slug: "baby-toddler-toys",
    parentId: "398",
  },
  {
    localId: "401",
    name: "Bath Toys",
    slug: "bath-toys",
    parentId: "398",
  },
  {
    localId: "402",
    name: "Crib Toys & Attachments",
    slug: "baby-crib-toys",
    parentId: "398",
  },
  {
    localId: "403",
    name: "Early Learning",
    slug: "kids-learning-education",
    parentId: "398",
  },
  {
    localId: "404",
    name: "Indoor Climbers & Structures",
    slug: "indoor-climbers-play-structures",
    parentId: "398",
  },
  {
    localId: "405",
    name: "Push & Pull Toys",
    slug: "push-pull-toys",
    parentId: "398",
  },
  {
    localId: "406",
    name: "Rocking & Spring Ride-Ons",
    slug: "car-seat-stroller-toys",
    parentId: "398",
  },
  {
    localId: "407",
    name: "Toyghor",
    slug: "shop",
    parentId: "398",
  },
  {
    localId: "408",
    name: "Remote Control & Vehicles",
    slug: "remote-control-toys-and-play-vehicles",
    parentId: "5",
  },
  {
    localId: "409",
    name: "Die-Cast Vehicles",
    slug: "die-cast-cars",
    parentId: "408",
  },
  {
    localId: "410",
    name: "RC Vehicles & Batteries",
    slug: "vehicles-batteries",
    parentId: "408",
  },
  {
    localId: "411",
    name: "Play Trains & Railway Sets",
    slug: "model-railway-and-train-sets",
    parentId: "408",
  },
  {
    localId: "412",
    name: "Play Vehicles",
    slug: "play-vehicles-toys",
    parentId: "408",
  },
  {
    localId: "413",
    name: "Drones & Accessories",
    slug: "drones-and-accessories",
    parentId: "408",
  },
  {
    localId: "414",
    name: "Drone Guru",
    slug: "shop",
    parentId: "408",
  },
  {
    localId: "415",
    name: "Takara Tomy",
    slug: "shop",
    parentId: "408",
  },
  {
    localId: "416",
    name: "Hot Wheels",
    slug: "shop",
    parentId: "408",
  },
  {
    localId: "417",
    name: "Khelna Bank BD",
    slug: "shop",
    parentId: "408",
  },
  {
    localId: "418",
    name: "Wright Flyer",
    slug: "shop",
    parentId: "408",
  },
  {
    localId: "419",
    name: "Sports & Outdoor Play",
    slug: "sports-and-outdoor-play",
    parentId: "5",
  },
  {
    localId: "420",
    name: "Fidget Spinners & Cubes",
    slug: "fidget-spinners",
    parentId: "419",
  },
  {
    localId: "421",
    name: "Kids Bikes & Accessories",
    slug: "outdoor-toys",
    parentId: "419",
  },
  {
    localId: "422",
    name: "Swimming Pool & Water Toys",
    slug: "swimming-pool-and-water-toys",
    parentId: "419",
  },
  {
    localId: "423",
    name: "Outdoor Toys",
    slug: "sports-outdoor-toys",
    parentId: "419",
  },
  {
    localId: "424",
    name: "Play Tents & Tunnels",
    slug: "play-tents-tunnels",
    parentId: "419",
  },
  {
    localId: "425",
    name: "Boxing",
    slug: "kids-boxing",
    parentId: "419",
  },
  {
    localId: "426",
    name: "Play Sets",
    slug: "play-sets-and-playground-equipment",
    parentId: "419",
  },
  {
    localId: "427",
    name: "Sports Play",
    slug: "kids-sports-play-equipment",
    parentId: "419",
  },
  {
    localId: "428",
    name: "Kids Tricycles",
    slug: "tricycles-bicycles",
    parentId: "419",
  },
  {
    localId: "429",
    name: "Toys Sports",
    slug: "sports-toys",
    parentId: "419",
  },
  {
    localId: "430",
    name: "ACI Captain Toys",
    slug: "shop",
    parentId: "419",
  },
  {
    localId: "431",
    name: "Traditional Games",
    slug: "traditional-games",
    parentId: "5",
  },
  {
    localId: "432",
    name: "Board Games",
    slug: "board-games",
    parentId: "431",
  },
  {
    localId: "433",
    name: "Card Games",
    slug: "card-games",
    parentId: "431",
  },
  {
    localId: "434",
    name: "Game Room Games",
    slug: "game-room-games",
    parentId: "431",
  },
  {
    localId: "435",
    name: "Smartphones",
    slug: "smartphones",
    parentId: "6",
  },
  {
    localId: "436",
    name: "Xiaomi Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "437",
    name: "realme Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "438",
    name: "Infinix Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "439",
    name: "Samsung Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "440",
    name: "OPPO Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "441",
    name: "vivo Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "442",
    name: "Apple Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "443",
    name: "Motorola Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "444",
    name: "Symphony Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "445",
    name: "Tecno Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "446",
    name: "Walton Phones",
    slug: "smartphones",
    parentId: "435",
  },
  {
    localId: "447",
    name: "Pre-owned Phones",
    slug: "used-mobile-phones",
    parentId: "435",
  },
  {
    localId: "448",
    name: "Feature Phone",
    slug: "featurephones",
    parentId: "6",
  },
  {
    localId: "449",
    name: "Nokia Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "450",
    name: "Symphony Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "451",
    name: "Walton Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "452",
    name: "Benco Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "453",
    name: "Agetel Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "454",
    name: "Bengal Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "455",
    name: "Geo Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "456",
    name: "Gphone Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "457",
    name: "Tinmo Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "458",
    name: "5 Star Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "459",
    name: "Linnex Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "460",
    name: "bytwo Feature Phones",
    slug: "featurephones",
    parentId: "448",
  },
  {
    localId: "461",
    name: "Tablets",
    slug: "tablets",
    parentId: "6",
  },
  {
    localId: "462",
    name: "Cameras",
    slug: "camera",
    parentId: "6",
  },
  {
    localId: "463",
    name: "Canon",
    slug: "dslr-hybrid-cameras",
    parentId: "462",
  },
  {
    localId: "464",
    name: "Nikon",
    slug: "dslr-hybrid-cameras",
    parentId: "462",
  },
  {
    localId: "465",
    name: "Sony",
    slug: "mirrorless",
    parentId: "462",
  },
  {
    localId: "466",
    name: "ZHIYUN",
    slug: "shop",
    parentId: "462",
  },
  {
    localId: "467",
    name: "GoPro",
    slug: "sport-action-camera",
    parentId: "462",
  },
  {
    localId: "468",
    name: "Insta 360",
    slug: "shop",
    parentId: "462",
  },
  {
    localId: "469",
    name: "Mirrorless",
    slug: "mirrorless",
    parentId: "462",
  },
  {
    localId: "470",
    name: "DSLR",
    slug: "dslr-hybrid-cameras",
    parentId: "462",
  },
  {
    localId: "471",
    name: "Video & Action Camcorder",
    slug: "camcorders",
    parentId: "462",
  },
  {
    localId: "472",
    name: "Security Cameras & Systems",
    slug: "security-cameras",
    parentId: "462",
  },
  {
    localId: "473",
    name: "Drones",
    slug: "drones",
    parentId: "462",
  },
  {
    localId: "474",
    name: "Car Cameras",
    slug: "car-cameras",
    parentId: "462",
  },
  {
    localId: "475",
    name: "Trendy Mobile Accessories",
    slug: "mobiles-tablets-accessories",
    parentId: "6",
  },
  {
    localId: "476",
    name: "Phone Cases",
    slug: "mobile-cases-covers",
    parentId: "475",
  },
  {
    localId: "477",
    name: "Phone Screen Protector",
    slug: "mobile-surface-screen-protectors",
    parentId: "475",
  },
  {
    localId: "478",
    name: "Cables & Converters",
    slug: "other-phone-tablet-accessories",
    parentId: "475",
  },
  {
    localId: "479",
    name: "Docks & Stands",
    slug: "wireless-speakers",
    parentId: "475",
  },
  {
    localId: "480",
    name: "Wall Chargers",
    slug: "phone-tablet-chargers",
    parentId: "475",
  },
  {
    localId: "481",
    name: "Power Banks",
    slug: "mobile-power-banks",
    parentId: "475",
  },
  {
    localId: "482",
    name: "Fashion Mobile Accessories",
    slug: "accessories-fashion",
    parentId: "475",
  },
  {
    localId: "483",
    name: "Hontinga Accessories",
    slug: "mobile-cases-covers",
    parentId: "475",
  },
  {
    localId: "484",
    name: "Baseus Accessories",
    slug: "mobiles-tablets-accessories",
    parentId: "475",
  },
  {
    localId: "485",
    name: "LENUO Accessories",
    slug: "mobile-cases-covers",
    parentId: "475",
  },
  {
    localId: "486",
    name: "CASIFY Accessories",
    slug: "mobiles-tablets-accessories",
    parentId: "475",
  },
  {
    localId: "487",
    name: "Xundd Accessories",
    slug: "mobile-cases-covers",
    parentId: "475",
  },
  {
    localId: "488",
    name: "Projectors",
    slug: "computing-projectors",
    parentId: "6",
  },
  {
    localId: "489",
    name: "Projector Screens",
    slug: "video-projector-screens",
    parentId: "489",
  },
  {
    localId: "490",
    name: "Gaming Console",
    slug: "gaming-consoles",
    parentId: "6",
  },
  {
    localId: "491",
    name: "PlayStation Console",
    slug: "playstation-consoles",
    parentId: "490",
  },
  {
    localId: "492",
    name: "PlayStation Games",
    slug: "playstation-games",
    parentId: "490",
  },
  {
    localId: "493",
    name: "PlayStation Controller",
    slug: "gaming-controllers",
    parentId: "490",
  },
  {
    localId: "494",
    name: "Nintendo Games",
    slug: "nintendo-games",
    parentId: "490",
  },
  {
    localId: "495",
    name: "Nintendo Consoles",
    slug: "nintendo-consoles",
    parentId: "490",
  },
  {
    localId: "496",
    name: "Xbox Games",
    slug: "xbox-games",
    parentId: "490",
  },
  {
    localId: "497",
    name: "Xbox Consoles",
    slug: "xbox-consoles",
    parentId: "490",
  },
  {
    localId: "498",
    name: "Other Gaming Consoles",
    slug: "gaming-others",
    parentId: "490",
  },
  {
    localId: "499",
    name: "TV Box",
    slug: "tv-receivers",
    parentId: "6",
  },
  {
    localId: "500",
    name: "Audio",
    slug: "audio",
    parentId: "6",
  },
  {
    localId: "501",
    name: "Headphones & Headsets",
    slug: "headphones-headsets",
    parentId: "500",
  },
  {
    localId: "502",
    name: "Bluetooth Speaker",
    slug: "portable-speakers",
    parentId: "500",
  },
  {
    localId: "503",
    name: "WearableSmartwatches",
    slug: "wearable-technology",
    parentId: "6",
  },
  {
    localId: "504",
    name: "Smartwatches",
    slug: "smart-watches",
    parentId: "503",
  },
  {
    localId: "505",
    name: "Laptops",
    slug: "laptops",
    parentId: "6",
  },
  {
    localId: "506",
    name: "Apple",
    slug: "apple",
    parentId: "505",
  },
  {
    localId: "507",
    name: "ASUS",
    slug: "shop",
    parentId: "505",
  },
  {
    localId: "508",
    name: "Acer",
    slug: "acer",
    parentId: "505",
  },
  {
    localId: "509",
    name: "Dell",
    slug: "dell",
    parentId: "505",
  },
  {
    localId: "510",
    name: "HP",
    slug: "hp",
    parentId: "505",
  },
  {
    localId: "511",
    name: "Lenovo",
    slug: "lenovo",
    parentId: "505",
  },
  {
    localId: "512",
    name: "Microsoft",
    slug: "microsoft",
    parentId: "505",
  },
  {
    localId: "513",
    name: "MSI",
    slug: "laptops",
    parentId: "505",
  },
  {
    localId: "514",
    name: "Realme",
    slug: "laptops",
    parentId: "505",
  },
  {
    localId: "515",
    name: "Walton",
    slug: "shop",
    parentId: "505",
  },
  {
    localId: "516",
    name: "Gaming Laptops",
    slug: "gaming-laptops",
    parentId: "505",
  },
  {
    localId: "517",
    name: "Daraz Like New",
    slug: "computers-laptops-used",
    parentId: "505",
  },
  {
    localId: "518",
    name: "Television",
    slug: "televisions",
    parentId: "7",
  },
  {
    localId: "519",
    name: "Smart Television",
    slug: "smart-tvs",
    parentId: "518",
  },
  {
    localId: "520",
    name: "LED Televisions",
    slug: "led-tvs",
    parentId: "518",
  },
  {
    localId: "521",
    name: "OLED Televisions",
    slug: "oled-tvs",
    parentId: "518",
  },
  {
    localId: "522",
    name: "Haier Televisions",
    slug: "televisions",
    parentId: "518",
  },
  {
    localId: "523",
    name: "Walton Televisions",
    slug: "televisions",
    parentId: "518",
  },
  {
    localId: "524",
    name: "Samsung Televisions",
    slug: "samsung",
    parentId: "518",
  },
  {
    localId: "525",
    name: "Vision Televisions",
    slug: "vision-1",
    parentId: "518",
  },
  {
    localId: "526",
    name: "Xiaomi Televisions",
    slug: "xiaomi--mi",
    parentId: "518",
  },
  {
    localId: "527",
    name: "Sony Televisions",
    slug: "sony",
    parentId: "518",
  },
  {
    localId: "528",
    name: "Singer Televisions",
    slug: "televisions",
    parentId: "518",
  },
  {
    localId: "529",
    name: "Minister Televisions",
    slug: "minister-brand",
    parentId: "518",
  },
  {
    localId: "530",
    name: "Home Audio",
    slug: "audio",
    parentId: "7",
  },
  {
    localId: "531",
    name: "Soundbars",
    slug: "sound-bars",
    parentId: "530",
  },
  {
    localId: "532",
    name: "Home Entertainment",
    slug: "home-theater",
    parentId: "530",
  },
  {
    localId: "533",
    name: "Bluetooth Speaker",
    slug: "portable-speakers",
    parentId: "530",
  },
  {
    localId: "534",
    name: "TV & Video Device",
    slug: "tv-accessories",
    parentId: "7",
  },
  {
    localId: "535",
    name: "TV Receivers",
    slug: "tv-receivers",
    parentId: "534",
  },
  {
    localId: "536",
    name: "TV Remote Controllers",
    slug: "tv-remote-controllers",
    parentId: "534",
  },
  {
    localId: "537",
    name: "Cables",
    slug: "tv-cables",
    parentId: "534",
  },
  {
    localId: "538",
    name: "Wall Mounts & Protectors",
    slug: "projectors",
    parentId: "534",
  },
  {
    localId: "539",
    name: "Blu-Ray/ DVD Players",
    slug: "blu-ray-players",
    parentId: "534",
  },
  {
    localId: "540",
    name: "Cooling & Heating",
    slug: "cooling-heating",
    parentId: "7",
  },
  {
    localId: "541",
    name: "Air Purifiers",
    slug: "air-purifiers",
    parentId: "540",
  },
  {
    localId: "542",
    name: "Humidifiers",
    slug: "air-purifiers-humidifiers",
    parentId: "540",
  },
  {
    localId: "543",
    name: "Heaters",
    slug: "heaters",
    parentId: "540",
  },
  {
    localId: "544",
    name: "Water Heaters",
    slug: "hot-water-systems",
    parentId: "540",
  },
  {
    localId: "545",
    name: "Kitchen Appliances",
    slug: "cooking-appliances",
    parentId: "7",
  },
  {
    localId: "546",
    name: "Cooktops & Ranges",
    slug: "cooktops",
    parentId: "545",
  },
  {
    localId: "547",
    name: "Gas Stoves",
    slug: "electric-cooktops",
    parentId: "545",
  },
  {
    localId: "548",
    name: "Ovens",
    slug: "large-ovens",
    parentId: "545",
  },
  {
    localId: "549",
    name: "Range Hoods",
    slug: "exhausts-rangehoods",
    parentId: "545",
  },
  {
    localId: "550",
    name: "Refrigerators",
    slug: "refrigerators",
    parentId: "7",
  },
  {
    localId: "551",
    name: "Samsung",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "552",
    name: "Walton",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "553",
    name: "Haier",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "554",
    name: "Singer",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "555",
    name: "Myone",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "556",
    name: "Sharp",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "557",
    name: "Minister",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "558",
    name: "Whirlpool",
    slug: "refrigerators",
    parentId: "550",
  },
  {
    localId: "559",
    name: "Deep Freezer",
    slug: "freezers",
    parentId: "7",
  },
  {
    localId: "560",
    name: "Sharp",
    slug: "freezers",
    parentId: "559",
  },
  {
    localId: "561",
    name: "Haier",
    slug: "freezers",
    parentId: "559",
  },
  {
    localId: "562",
    name: "Walton",
    slug: "freezers",
    parentId: "559",
  },
  {
    localId: "563",
    name: "Singer",
    slug: "freezers",
    parentId: "559",
  },
  {
    localId: "564",
    name: "Marcel",
    slug: "freezers",
    parentId: "559",
  },
  {
    localId: "565",
    name: "Minister",
    slug: "freezers",
    parentId: "559",
  },
  {
    localId: "566",
    name: "Electra",
    slug: "freezers",
    parentId: "559",
  },
  {
    localId: "567",
    name: "Microwaves",
    slug: "microwave",
    parentId: "7",
  },
  {
    localId: "568",
    name: "Samsung",
    slug: "microwave",
    parentId: "567",
  },
  {
    localId: "569",
    name: "Sharp",
    slug: "microwave",
    parentId: "567",
  },
  {
    localId: "570",
    name: "Singer",
    slug: "microwave",
    parentId: "567",
  },
  {
    localId: "571",
    name: "Panasonic",
    slug: "microwave",
    parentId: "567",
  },
  {
    localId: "572",
    name: "Air Conditioners",
    slug: "air-conditioners",
    parentId: "7",
  },
  {
    localId: "573",
    name: "Gree AC",
    slug: "air-conditioners",
    parentId: "572",
  },
  {
    localId: "574",
    name: "Midea AC",
    slug: "air-conditioners",
    parentId: "572",
  },
  {
    localId: "575",
    name: "Haier AC",
    slug: "air-conditioners",
    parentId: "572",
  },
  {
    localId: "576",
    name: "Singer AC",
    slug: "air-conditioners",
    parentId: "572",
  },
  {
    localId: "577",
    name: "Minister AC",
    slug: "air-conditioners",
    parentId: "572",
  },
  {
    localId: "578",
    name: "Viomi AC",
    slug: "air-conditioners",
    parentId: "572",
  },
  {
    localId: "579",
    name: "Walton AC",
    slug: "air-conditioners",
    parentId: "572",
  },
  {
    localId: "580",
    name: "Vision Cooler",
    slug: "portable-ac",
    parentId: "572",
  },
  {
    localId: "581",
    name: "Gree Cooler",
    slug: "portable-ac",
    parentId: "572",
  },
  {
    localId: "582",
    name: "Walton Cooler",
    slug: "portable-ac",
    parentId: "572",
  },
  {
    localId: "583",
    name: "Orient Cooler",
    slug: "portable-ac",
    parentId: "572",
  },
  {
    localId: "584",
    name: "Fans",
    slug: "all-fans",
    parentId: "7",
  },
  {
    localId: "585",
    name: "Ceiling Fans",
    slug: "ceiling-fan",
    parentId: "584",
  },
  {
    localId: "586",
    name: "Mini Fans",
    slug: "mini-fans",
    parentId: "584",
  },
  {
    localId: "587",
    name: "Table Fans",
    slug: "table-fan",
    parentId: "584",
  },
  {
    localId: "588",
    name: "Other Fans",
    slug: "other-fan",
    parentId: "584",
  },
  {
    localId: "589",
    name: "Stand Fan",
    slug: "stand-fan",
    parentId: "584",
  },
  {
    localId: "590",
    name: "Small Appliances",
    slug: "small-kitchen-appliances",
    parentId: "7",
  },
  {
    localId: "591",
    name: "Blender",
    slug: "food-preparation",
    parentId: "590",
  },
  {
    localId: "592",
    name: "Rice Cookers",
    slug: "rice-cookers",
    parentId: "590",
  },
  {
    localId: "593",
    name: "Electric Kettles",
    slug: "electric-kettles-thermo-pots",
    parentId: "590",
  },
  {
    localId: "594",
    name: "Coffee Machines",
    slug: "espresso-machines",
    parentId: "590",
  },
  {
    localId: "595",
    name: "Fryers",
    slug: "fryers",
    parentId: "590",
  },
  {
    localId: "596",
    name: "Other Small Kitchen Appliances",
    slug: "specialty-cookware",
    parentId: "590",
  },
  {
    localId: "597",
    name: "Toasters",
    slug: "toasters",
    parentId: "590",
  },
  {
    localId: "598",
    name: "Vacuum Cleaners",
    slug: "vacuum-cleaners",
    parentId: "590",
  },
  {
    localId: "599",
    name: "Irons",
    slug: "ironing-laundry-appliances",
    parentId: "590",
  },
  {
    localId: "600",
    name: "Sewing Machines",
    slug: "sewing-machines",
    parentId: "590",
  },
  {
    localId: "601",
    name: "Water PurifiersKentMideaPureitHavells",
    slug: "water-dispensers-purifiers",
    parentId: "7",
  },
  {
    localId: "602",
    name: "Kent",
    slug: "water-dispensers-purifiers",
    parentId: "601",
  },
  {
    localId: "603",
    name: "Midea",
    slug: "water-dispensers-purifiers",
    parentId: "601",
  },
  {
    localId: "604",
    name: "Pureit",
    slug: "water-dispensers-purifiers",
    parentId: "601",
  },
  {
    localId: "605",
    name: "Havells",
    slug: "water-dispensers-purifiers",
    parentId: "601",
  },
  {
    localId: "606",
    name: "Audio",
    slug: "audio",
    parentId: "8",
  },
  {
    localId: "607",
    name: "Headphones & Headsets",
    slug: "headphones-headsets",
    parentId: "606",
  },
  {
    localId: "608",
    name: "Bluetooth Speaker",
    slug: "portable-speakers",
    parentId: "606",
  },
  {
    localId: "609",
    name: "Smart Speaker",
    slug: "smart-speakers",
    parentId: "606",
  },
  {
    localId: "610",
    name: "Live Sound & Stage Equipment",
    slug: "live-sound-stage",
    parentId: "606",
  },
  {
    localId: "611",
    name: "Wireless Earbuds",
    slug: "wireless-earbuds",
    parentId: "606",
  },
  {
    localId: "612",
    name: "Portable Players",
    slug: "mp3-players-ipods",
    parentId: "606",
  },
  {
    localId: "613",
    name: "Wearable",
    slug: "wearable-technology",
    parentId: "8",
  },
  {
    localId: "614",
    name: "Smartwatches",
    slug: "smart-watches",
    parentId: "613",
  },
  {
    localId: "615",
    name: "Fitness & Activity Trackers",
    slug: "fitness-trackers",
    parentId: "613",
  },
  {
    localId: "616",
    name: "Virtual Reality",
    slug: "virtual-reality",
    parentId: "613",
  },
  {
    localId: "617",
    name: "Smartwatches Accessories",
    slug: "smartwatches-accessories",
    parentId: "613",
  },
  {
    localId: "618",
    name: "GadgetsLaser pointers",
    slug: "gaming-gadgets",
    parentId: "8",
  },
  {
    localId: "619",
    name: "Laser pointers",
    slug: "laser-pointers-gadgets",
    parentId: "619",
  },
  {
    localId: "620",
    name: "Computer Accessories",
    slug: "computing-peripherals-accessories",
    parentId: "8",
  },
  {
    localId: "621",
    name: "Monitors",
    slug: "computer-monitors",
    parentId: "620",
  },
  {
    localId: "622",
    name: "Mice",
    slug: "computer-accessories-mouse",
    parentId: "620",
  },
  {
    localId: "623",
    name: "PC Audio",
    slug: "pc-audio",
    parentId: "620",
  },
  {
    localId: "624",
    name: "Keyboards",
    slug: "keyboard",
    parentId: "620",
  },
  {
    localId: "625",
    name: "Mice & Keyboard Combos",
    slug: "mice-keyboard-combos",
    parentId: "620",
  },
  {
    localId: "626",
    name: "Power Cord & Adaptors",
    slug: "computer-adapters",
    parentId: "620",
  },
  {
    localId: "627",
    name: "Storage",
    slug: "computing-storage",
    parentId: "8",
  },
  {
    localId: "628",
    name: "External Hard Drives",
    slug: "external-hard-drives",
    parentId: "627",
  },
  {
    localId: "629",
    name: "Internal Hard Drives",
    slug: "internal-hard-drives",
    parentId: "627",
  },
  {
    localId: "630",
    name: "Flash Drives",
    slug: "usb-flash-drives",
    parentId: "627",
  },
  {
    localId: "631",
    name: "OTG Drives",
    slug: "storage-otg-drives",
    parentId: "627",
  },
  {
    localId: "632",
    name: "Internal Solid State Drives",
    slug: "solid-state-drives",
    parentId: "627",
  },
  {
    localId: "633",
    name: "External Solid State Drives",
    slug: "external-solid-state-drive",
    parentId: "627",
  },
  {
    localId: "634",
    name: "Printer",
    slug: "printers-scanners",
    parentId: "8",
  },
  {
    localId: "635",
    name: "Printers",
    slug: "multi-function-printers",
    parentId: "634",
  },
  {
    localId: "636",
    name: "Ink",
    slug: "printer-ink",
    parentId: "634",
  },
  {
    localId: "637",
    name: "Toner",
    slug: "ink-cartridges-toners",
    parentId: "634",
  },
  {
    localId: "638",
    name: "Printer Stands",
    slug: "printer-stands",
    parentId: "634",
  },
  {
    localId: "639",
    name: "Fax Machines",
    slug: "fax-machines",
    parentId: "634",
  },
  {
    localId: "640",
    name: "Computer Components",
    slug: "components-spare-parts",
    parentId: "8",
  },
  {
    localId: "641",
    name: "Graphic Cards",
    slug: "computer-graphic-cards",
    parentId: "640",
  },
  {
    localId: "642",
    name: "Desktop Casings",
    slug: "casing",
    parentId: "640",
  },
  {
    localId: "643",
    name: "Motherboards",
    slug: "motherboard",
    parentId: "640",
  },
  {
    localId: "644",
    name: "Fans & Heatsinks",
    slug: "fans-heatsinks",
    parentId: "640",
  },
  {
    localId: "645",
    name: "RAM",
    slug: "ram",
    parentId: "640",
  },
  {
    localId: "646",
    name: "Processors",
    slug: "processor",
    parentId: "640",
  },
  {
    localId: "647",
    name: "Network Components",
    slug: "networking",
    parentId: "8",
  },
  {
    localId: "648",
    name: "Access Points",
    slug: "access-points",
    parentId: "647",
  },
  {
    localId: "649",
    name: "Modems",
    slug: "modems",
    parentId: "647",
  },
  {
    localId: "650",
    name: "Network Interface Cards",
    slug: "network-interface-cards",
    parentId: "647",
  },
  {
    localId: "651",
    name: "Network Switches",
    slug: "network-switch",
    parentId: "647",
  },
  {
    localId: "652",
    name: "Routers",
    slug: "routers",
    parentId: "647",
  },
  {
    localId: "653",
    name: "Wireless USB Adapters",
    slug: "wireless-usb-adapters",
    parentId: "647",
  },
  {
    localId: "654",
    name: "Software",
    slug: "software",
    parentId: "8",
  },
  {
    localId: "655",
    name: "Educational Media",
    slug: "educational-media",
    parentId: "654",
  },
  {
    localId: "656",
    name: "Operating System",
    slug: "operating-system",
    parentId: "654",
  },
  {
    localId: "657",
    name: "PC Games",
    slug: "pc-games",
    parentId: "654",
  },
  {
    localId: "658",
    name: "Security Software",
    slug: "security-software",
    parentId: "654",
  },
  {
    localId: "659",
    name: "Camera Accessories",
    slug: "camera-accessories",
    parentId: "8",
  },
  {
    localId: "660",
    name: "Canon",
    slug: "camera-accessories",
    parentId: "659",
  },
  {
    localId: "661",
    name: "Nikon",
    slug: "camera-accessories",
    parentId: "659",
  },
  {
    localId: "662",
    name: "Sony",
    slug: "camera-accessories",
    parentId: "659",
  },
  {
    localId: "663",
    name: "ZHIYUN",
    slug: "camera-accessories",
    parentId: "659",
  },
  {
    localId: "664",
    name: "Ulanzi",
    slug: "camera-accessories",
    parentId: "659",
  },
  {
    localId: "665",
    name: "Yunteg",
    slug: "camera-accessories",
    parentId: "659",
  },
  {
    localId: "666",
    name: "Lighting & Studio Equipment",
    slug: "lighting-studio-equipment",
    parentId: "659",
  },
  {
    localId: "667",
    name: "Tripods & Monopods",
    slug: "tripods-monopods",
    parentId: "659",
  },
  {
    localId: "668",
    name: "Gimbals & Stabilizers",
    slug: "gimbals-stabilizer",
    parentId: "659",
  },
  {
    localId: "669",
    name: "Sports & Action Camera Accessories",
    slug: "sport-action-camera-accessories",
    parentId: "659",
  },
  {
    localId: "670",
    name: "Memory Cards",
    slug: "memory-cards",
    parentId: "659",
  },
  {
    localId: "671",
    name: "Batteries",
    slug: "camera-batteries",
    parentId: "659",
  },
];
