const fs = require("fs");

const data = {
  Barishal: {
    Barguna: [
      "Amtali",
      "Bamna",
      "Barguna Government College",
      "Barguna Sadar",
      "Barguna Taltali",
      "Barguna West Police Farry",
      "Betagi",
      "Darul Ulum",
      "Kakchira",
      "Nali Bandar",
      "Patharghata",
    ],
    "Barishal - Agailjhara": [
      "Agailjhara Bazar",
      "Agailjhara Sadar",
      "Gaila",
      "Paisarhat",
    ],
    "Barishal - Babuganj": [
      "Babuganj Sadar",
      "Barishal Cadet College",
      "Chandpasha",
      "Dehergoti",
      "Guthia",
      "Madhabpasha",
      "Nizamuddin College",
      "Rahamatpur",
      "Thakur Mallik",
    ],
    "Barishal - Bakerganj": [
      "Bakerganj Darial",
      "Charamandi",
      "Garuria",
      "Kalaskati",
      "Padri Shibpur",
      "Sahebganj",
    ],
    "Barishal - Gouranadi": [
      "Batajor",
      "Gouranadi Launch Ghat",
      "Gouranadi Sadar",
      "Kashemabad",
      "Mridha market",
      "Tarki Bandar",
    ],
    "Barishal - Hizla": ["Barajalia Sadar", "Memania", "Osman Manjil"],
    "Barishal - Mehendiganj": [
      "Langutia",
      "Laskarpur",
      "Mehendiganj Sadar",
      "Ulania",
    ],
    "Barishal - Muladi": [
      "Bara Madhab rayer char",
      "Charkalekhan",
      "Kazirchar",
      "Muladi Sadar",
    ],
    "Barishal - Town": [
      "Barishal Kazipara",
      "Barishal Sadar",
      "Bibir Pukur",
      "Bukhainagar",
      "Chahutpur",
      "Jaguarhat",
      "Kashipur",
      "Kawnia",
      "Moth Baria",
      "Natun Bazar",
      "Patang",
      "Rajmahal",
      "Rupatali",
      "Sadar Upazila",
      "Sagardi",
      "Saheberhat",
      "Sugandia",
      "Taltali",
      "Tia Khali",
    ],
    "Barishal - Uzirpur": [
      "Dakuarhat",
      "Dhamura",
      "Jugirkanda",
      "Shikarpur",
      "Uzirpur Bazar",
      "Uzirpur Sadar",
      "Wazirpur Bazar",
    ],
    Bhola: [
      "Abhohawa Office Road",
      "Ali Nagar",
      "Bangla School Mor",
      "Banker Hat",
      "Bhola Bapta",
      "Bhola Boys School Road",
      "Bhola Central Post Office",
      "Bhola Collage Road",
      "Bhola Girls Collage Road",
      "Bhola Natun Bazar",
      "Bhola Pranishompod Road",
      "Bhola Sadar",
      "Bhola Sadar Hospital Road",
      "Bhola Ukil Para",
      "Borhanuddin UPO",
      "Charfashion",
      "Char Kalmi",
      "Chornoyabad",
      "Chorshami",
      "Daurihat",
      "Dorga Road",
      "Doulatkhan",
      "Dularhat",
      "Gazaria",
      "Hajipur",
      "Hajirhat",
      "Hatshoshiganj",
      "Jamiralota",
      "Joynagar",
      "Kalibari Road",
      "Kalikhola Road",
      "Keramatganj",
      "Lalmohan UPO",
      "Mirzakalu",
      "Monpura",
      "Mostofa Kamal Bus Stand",
      "Nasir Mazi",
      "New Elisha Bus Stand",
      "Nobi Pur",
      "Old Elisha Bus Stand",
      "P.T.I Road",
      "Pouro Khathali",
      "Roton Pur",
      "Sodurchar",
      "Tazumuddin",
      "Western Para",
    ],
    Jhalokati: [
      "Alam Market",
      "Amtola Bazar",
      "Amua",
      "Amua Bazar",
      "Amua Zero Point",
      "Aorabunia Dokkhinpar Bazar",
      "Bablatola Bazar",
      "Baidarapur",
      "Banai Bazar",
      "Bashonda",
      "Baukathi",
      "Beerkathi",
      "Bhairabpasha",
      "Bhavanipur Launch Station",
      "Binapani Bazar",
      "Binoy Khathi",
      "Bisic Silponogori Jhalokhati",
      "Bot Tola Bazar",
      "C&B Bazar",
      "Centrer Hat",
      "Chailar Char",
      "Charukhan",
      "Dapdapia Launch Ghat",
      "Darul Habib Khanka Sharif Dapdapia Barishal",
      "Deulkati",
      "Dibakorkathi",
      "Dopdipia Fish Bazar",
      "Eidgar Bazar",
      "Fokir Market",
      "Gabha",
      "Gabkhan",
      "Galua Bazar",
      "Gopalpur Pochchim Para",
      "Guachitra Bazar",
      "Guhuder Bazar",
      "Hadua Bazar",
      "Hodua Launch Terminal",
      "Islamia Bazar",
      "Jhalokati Sadar",
      "Kachua Ferry Terminal",
      "Kathalia",
      "Khejurtala Bazar",
      "Kirtipasha",
      "Kolakopa Bazar",
      "Kulkhathi Bazar",
      "Latimsar",
      "Magar Bazar",
      "Mahtab Malta Bagan",
      "Manpasha",
      "Mohajon Bazar",
      "Mollar Hatt Bazar",
      "Morichbunia Bazar",
      "Mothbari",
      "Munsirabad Bazar Jhalokati Shouljalia",
      "Nabagram",
      "Nalchhiti",
      "Nathullabadh",
      "Navagram",
      "Niamatee",
      "Notun Hath Bazar Jhalokathi Ranapasha",
      "Noyarasta Bazar",
      "Ostakhan Bazar",
      "Panchagram Bazar",
      "Patikhal Ghata Bazar",
      "Pingri",
      "Ponabalia Bazar",
      "Protap",
      "Rajapur",
      "Rajapur Jhalokatii",
      "Satani Bazar",
      "Shakherhat",
      "Shameer Hat",
      "Shekherhat",
      "Shoulajalia",
      "South Palot Launch Terminal",
      "Taltola Bazar",
      "Tekerhat Bazar",
      "Ukel Bazzar",
      "Uttar Bikna",
      "Zahatola Bazar",
    ],
    Patuakhali: [
      "Auliapur",
      "Bagabandar",
      "Barabighai",
      "Bauphal",
      "Birpasha",
      "Char Montaz",
      "Dashmina",
      "Dumkee",
      "Galachipa",
      "Gazipur Bandar",
      "Hetalia Badhghat",
      "Jainkathi",
      "Kalaia",
      "Kalapara - Galachipa",
      "Kalishari",
      "Katpotti",
      "Khepupara",
      "Kuakata",
      "Lebukhali",
      "Lohalia",
      "Mahipur",
      "Marichbunia",
      "Mirjaganj Sarak",
      "Mitha Pukur Par",
      "Moukaran",
      "Mukul Cinema Hall",
      "Nobab Para",
      "Patuakhali Banani",
      "Patuakhali Jailkhana Road",
      "Patuakhali Medical College Hospital",
      "Patuakhali Notun Bazar",
      "Patuakhali Pourosova",
      "Patuakhali Puran Bazar",
      "Patuakhali Sadar",
      "Patuakhali Shilpokola Academy",
      "Rahimabad",
      "Rangabali",
      "Subidkhali",
    ],
    Pirojpur: [
      "Amla Para",
      "Banaripara",
      "Betmor Natun Hat",
      "Bhandaria",
      "Bolaka Club Road",
      "Bolassor Bridge",
      "Boro Mosjid",
      "C.I Para",
      "Chakhar",
      "Damudar Bridge",
      "Darus Sunnat",
      "Dhaoa",
      "Dokhin Shikar Pur",
      "Dopa Bara",
      "Duppasa",
      "Gulishakhali",
      "Halta",
      "Hularhat",
      "Jalabari",
      "Jolagati",
      "Joykul",
      "Kanudashkathi",
      "Kaukhali",
      "Kaurikhara",
      "Keundia",
      "Masim Pur",
      "Matani Road",
      "Mathbaria",
      "Mohila College Road",
      "Muchi Para",
      "Nazirpur",
      "Nirer Goli",
      "Parerhat",
      "Pirojpur Adarsha Para",
      "Pirojpur Boropul",
      "Pirojpur Bot Tola",
      "Pirojpur College Road",
      "Pirojpur Dc Office",
      "Pirojpur Judge Court",
      "Pirojpur Lged",
      "Pirojpur New Bus Stand",
      "Pirojpur P.T.I Road",
      "Pirojpur Palpara",
      "Pirojpur Police Line",
      "Pirojpur Police Station",
      "Pirojpur Post Office",
      "Pirojpur Pouro Shoshan",
      "Pirojpur Puran Pouroshova Road",
      "Pirojpur Sadar",
      "Pirojpur Sadar Hospital",
      "Pirojpur Sadar Thana",
      "Pirojpur Surgicare",
      "Pirojpur Town Club",
      "Pirojpur Ukil Para",
      "Rajar Hat",
      "Sheik Para",
      "Shikha Office",
      "Shilarganj",
      "Sriramkathi",
      "Swarupkathi",
      "Tiarkhali",
      "Tushkhali",
      "Yasinkhar Pol",
    ],
  },
  Chattogram: {
    Bandarban: [
      "Alikadam",
      "Balaghata",
      "Bandarban Sadar",
      "Naikhong",
      "Naikhongchari",
      "Roanchhari",
      "Ruma",
      "Thanchi",
      "Thanchi Lama",
    ],
    Banshkhali: [
      "Haliapara",
      "Jaldi Banigram",
      "Jaldi Gunagari",
      "Jaldi Khan Bahadur",
      "Jaldi Sadar",
      "Kalamarchara",
      "Matarbari",
      "Napora",
      "Panirchara",
      "Sonadia",
    ],
    Basurhat: ["Basurhat Basur Hat", "Basurhat Charhajari"],
    Begumganj: [
      "Begumganj Alaiarpur",
      "Begumganj Amisha Para",
      "Begumganj Banglabazar",
      "Begumganj Bazra",
      "Begumganj Bhabani Jibanpur",
      "Begumganj Choumohani",
      "Begumganj Dauti",
      "Begumganj Durgapur",
      "Begumganj Gopalpur",
      "Begumganj Jamidar Hat",
      "Begumganj Joyag",
      "Begumganj Joynarayanpur",
      "Begumganj Khalafat Bazar",
      "Begumganj Khalishpur",
      "Begumganj Maheshganj",
      "Begumganj Mir Owarishpur",
      "Begumganj Nadona",
      "Begumganj Nandiapara",
      "Begumganj Oachhekpur",
      "Begumganj Rajganj",
      "Begumganj Sadar",
      "Begumganj Sonaimuri",
      "Begumganj Tangirpar",
      "Begumganj Thanar Hat",
    ],
    Bilaichhari: ["Bilaichhari Bilaichhari"],
    Boalkhali: [
      "Boalkhali Charandwip",
      "Boalkhali Iqbal Park",
      "Boalkhali Kadurkhal",
      "Boalkhali Kanungopara",
      "Boalkhali Sadar",
      "Boalkhali Sakpura",
      "Boalkhali Saroatoli",
    ],
    Brahmanbaria: [
      "Akhaura",
      "Akhaura Gangasagar",
      "Banchharampur",
      "Bhadughar",
      "Bijoynagar",
      "Brahmanbaria Sadar",
      "Brahmanbaria Sadar Ashuganj",
      "Brahmanbaria Sadar Ashuganj Share",
      "Brahmanbaria Sadar Poun",
      "Brahmanbaria Sadar Talshahar",
      "Gokarna Ghat",
      "Harashpur",
      "Hujur Bari",
      "Nasirnagar",
      "Natai",
      "Suhilpur",
    ],
    "Brahmanbaria - Kasba": [
      "Kasba Chandidar",
      "Kasba Chargachh",
      "Kasba Gopinathpur",
      "Kasba Kuti",
      "Kasba Sadar",
      "Kullapathar",
      "Madla",
    ],
    "Brahmanbaria - Nabinagar": [
      "Nabinagar Jibanganj",
      "Nabinagar Kaitala",
      "Nabinagar Laubfatehpur",
      "Nabinagar Rasullabad",
      "Nabinagar Ratanpur",
      "Nabinagar Sadar",
      "Nabinagar Salimganj",
      "Nabinagar Shahapur",
      "Nabinagar Shamgram",
      "Nasirnagar Fandauk",
    ],
    "Brahmanbaria - Sarail": [
      "Sarail Chandura",
      "Sarail Sadar",
      "Sarail Shahbajpur",
    ],
    Chakaria: [
      "Chakaria Sadar",
      "Chiringga Badarkali",
      "Chiringga Chiringga S.O",
      "Chiringga Malumghat",
      "Chiringga Sadar",
      "Dulahazara",
      "Harbang",
      "Khutakhali Bazar",
    ],
    Chandanaish: [
      "East Joara Barma",
      "East Joara Dohazari",
      "East Joara East Joara",
      "East Joara Gachbaria",
    ],
    "Chandpur - Faridganj": [
      "Faridganj Chandra",
      "Faridganj Gridkaliandia",
      "Faridganj Islampur Shah Isain",
      "Faridganj Rampurbazar",
      "Faridganj Rupsha",
      "Faridganj Sadar",
    ],
    "Chandpur - Hajiganj": ["Hajiganj Bolakhal", "Hajiganj Hajiganj"],
    "Chandpur - Hayemchar": ["Hayemchar Gandamara", "Hayemchar Sadar"],
    "Chandpur - Kachua": [
      "Bedpur",
      "Kachua Rahima Nagar",
      "Kachua Sadar",
      "Kachua Shachar",
    ],
    "Chandpur - Matlab": [
      "Amuakandi",
      "Dakkhin Doulotpur",
      "Dakkhin Narayanpur",
      "Matlab Mohanpur",
      "Matlab Sadar",
      "Matlab Uttar Amiyapur",
      "Matlab Uttar Upazila Parishad",
      "Noyanogor",
      "Sujatpur Bazar",
    ],
    "Chandpur Sadar": [
      "Chandpur Chowrasta",
      "Chandpur Sadar Baburhat",
      "Chandpur Sadar Puranbazar",
      "Chandpur Sadar Sahatali",
    ],
    Chatkhil: [
      "Chatkhil Bansa Bazar",
      "Chatkhil Bodalcourt",
      "Chatkhil Dosh Gharia",
      "Chatkhil Karihati",
      "Chatkhil Khilpara",
      "Chatkhil Palla",
      "Chatkhil Rezzakpur",
      "Chatkhil Sadar",
      "Chatkhil Sahapur",
      "Chatkhil Sampara",
      "Chatkhil Shingbahura",
      "Chatkhil Solla",
    ],
    "Chattogram - Anowara": ["Anawara Battali", "Anawara Paroikora", "Chatory"],
    "Chattogram Sadar": [
      "Agrabad",
      "AK Khan",
      "Al- Amin Baria Madrasa",
      "Amin Jute Mills",
      "Anandabazar",
      "Bayezid Bostami",
      "Cepz",
      "Chandgaon",
      "Chattogram Airport",
      "Chattogram Bandar",
      "Chattogram Cantonment",
      "Chattogram Customs Acca",
      "Chattogram GPO",
      "Chattogram New Market",
      "Chattogram Politechnic Institute",
      "Chattogram Sailers Colony",
      "Chawkbazar",
      "Colonel Hat",
      "Combined Military Hospital (CMH)",
      "Dakkshin Pahartoli",
      "Double Mooring",
      "Firozshah",
      "GEC",
      "Jaldia Marine Academy",
      "Khulshi",
      "Kotwali",
      "Middle Patenga",
      "Mohard",
      "Nasirabad",
      "North Halishahar",
      "North Kattali",
      "Noyabazar",
      "Oxygen",
      "Pahartoli",
      "Panchlaish",
      "Patenga",
      "Rampura TSO",
      "Sadarghat",
      "South Halishahar",
      "South Kattali",
      "Wazedia",
    ],
    Chhagalnaia: [
      "Amjad Hat",
      "Bangla Bazar Haripur",
      "Bondua Dolotpur",
      "Box Mahmud",
      "Chhagalnaia Daraga Hat",
      "Chhagalnaia Maharajganj",
      "Chhagalnaia Puabashimulia",
      "Chhagalnaia Sadar",
      "Kalbat Bottoli Bazar",
      "Killadighi",
      "Puraton Muhuriganj Bazar",
      "Rezumia Bazar",
      "Shantir Bazar",
    ],
    "Comilla - Barura": [
      "Barura Murdafarganj",
      "Barura Poyalgachha",
      "Barura Sadar",
    ],
    "Comilla - Brahmanpara": [
      "Bagra",
      "Brahmanpara Sadar",
      "Chandla",
      "Shashidal",
      "Shidlai",
    ],
    "Comilla - Burichang": [
      "Adbarpur",
      "Burichang Maynamoti bazar",
      "Burichang Sadar",
    ],
    "Comilla - Chandina": [
      "Chandina Chandia",
      "Chandina Madhaiabazar",
      "Raj Kalibari",
    ],
    "Comilla - Choddagram": [
      "Chouddagram Batisa",
      "Chouddagram Chiora",
      "Chouddagram Upazila Health Complex",
    ],
    "Comilla - Daudkandi": [
      "Daudkandi Dashpara",
      "Daudkandi Daudkandi",
      "Daudkandi Eliotganj",
      "Daudkandi Gouripur",
    ],
    "Comilla - Davidhar": [
      "Companiganj",
      "Davidhar Barashalghar",
      "Davidhar Davidhar",
      "Davidhar Dhamtee",
      "Davidhar Gangamandal",
    ],
    "Comilla - Homna": ["Akhandapur", "Homna Homna", "Hujurkandi", "Mohonpur"],
    "Comilla Laksam": ["Gajimura", "Laksam Bipulasar", "Laksam Lakshamanpur"],
    "Comilla - Lalmai": ["Amratali", "Baghmara", "Lalmai Pahar", "Poranpur"],
    "Comilla Langalkot": [
      "Langalkot Chhariabazar",
      "Langalkot Chilpara",
      "Langalkot Dhalua",
      "Langalkot Gunabati",
    ],
    "Comilla - Meghna": [
      "Boro Kanda",
      "Chandanpur",
      "Manikar Char",
      "Meghna Luter Char",
      "Rampur Bazar",
      "Titir Char",
      "Vaor Khola",
    ],
    "Comilla - Monohorganj": [
      "Hasnabad Bazar",
      "Lakkhanpur",
      "Lalchandpur",
      "Monohorganj Sadar",
      "Natherpetua",
      "Shikchail",
    ],
    "Comilla - Muradnagar": [
      "Muradnagar Bangra",
      "Muradnagar Companyganj",
      "Muradnagar Muradnagar",
      "Muradnagar Pantibazar",
      "Muradnagar Ramchandarpur",
      "Muradnagar Sonakanda",
    ],
    "Comilla Sadar": [
      "Badurtola",
      "Baro Para",
      "Comilla Housing",
      "Comilla Sadar Comilla Contonment",
      "Comilla Sadar Courtbari",
      "Comilla Sadar Halimanagar",
      "Comilla Sadar Suaganj",
      "Dharmopur",
      "Kandirpar",
      "Kaptan Bazar",
      "Paduar Bazar",
      "Shashongachha",
      "Tomsom Bridge",
    ],
    "Cox's Bazar Sadar": [
      "Baharchora",
      "Bazarghata",
      "Cox's Bazar Bus Terminal",
      "Holiday Mor",
      "Kolatoli",
      "Laldighi Par",
      "Link Road",
    ],
    "Coxs Bazar Eidgaon Upazila": ["Eidgaon Union Parishad", "Pokkhali"],
    Daganbhuiyan: [
      "Badher Gora",
      "Bhuiyanr Hat",
      "Char Hakdi",
      "Char Laxigonj",
      "Chowdhuri Hat",
      "Daganbhuiyan Chhilonia",
      "Daganbhuiyan Dudmukha",
      "Daganbhuiyan Rajapur",
      "Daganbhuiyan Upazila Parishad",
      "Khushipur",
      "Mowlana Ghat Ferry Terminal",
      "Purba Chandrapur",
      "Sebar Hat",
      "Sindurpur Bazar",
      "South Karimpur Dagonbhuiyan Feni",
      "South Neaz Pur",
      "Taltoli Bazar",
    ],
    Diginala: ["Diginala Sadar"],
    Fatikchhari: [
      "Fatichhari Maiz Vandar Sharif",
      "Fatikchhari Fatikchhari",
      "Fatikchhari Harualchhari",
      "Fatikchhari Najirhat",
      "Fatikchhari Nanupur",
      "Fatikchhari Narayanhat",
    ],
    Feni: [
      "Amtoli Bazar",
      "Bhanga Takia Bazar Sharshadie",
      "Biroli Bazar Bridge",
      "Court Buliding",
      "Daud Pul",
      "Dharmapur Amin Bazar",
      "Feni Cadet College",
      "Feni Circuit House",
      "Feni Police Line",
      "Feni Polytechnic Institute",
      "Feni Sadar",
      "Feni Sadar Fazilpur",
      "Feni Sadar Hospital",
      "Feni Sadar Laskarhat",
      "Feni Stadium",
      "Feni TB Hospital",
      "Feni University",
      "Grand Trunk Road",
      "Grand Trunk Road Squre",
      "Gunabati Railway Station",
      "Hazir Bazar Post OfficeSharshadie",
      "Ja Academy",
      "Kalidaha- Laskarhat Rd",
      "Khaiyara The Head",
      "Lalpul",
      "Laskarhat Post Office",
      "Laskar Hat S C Laha Institution",
      "Mastar Para",
      "Mohipal",
      "Panchgachia Bazar",
      "Parshuram Munsirhat",
      "Parshuram Peerboxhat",
      "Petro Bangla",
      "Pirganj Laldigi",
      "Rampur",
      "Ranir Hat",
      "Santi Company Road",
      "Shodeb Pur",
      "Shohid Selina Parvin Road",
      "Shuvapur",
      "Tewmuhuni Bazar",
      "Ukil Para",
    ],
    Hathazari: [
      "Hathazari Chitt.University",
      "Hathazari Fatahabad",
      "Hathazari Gorduara",
      "Hathazari Hathazari",
      "Hathazari Katirhat",
      "Hathazari Madrasa",
      "Hathazari Mirzapur",
      "Hathazari Nuralibari",
      "Hathazari Yunus Nagar",
    ],
    Hatiya: ["Hatiya Afazia", "Hatiya Sadar", "Hatiya Tamoraddi"],
    Juraichhari: ["Jarachhari Jarachhari"],
    Kaptai: [
      "Kaptai Chandraghona",
      "Kaptai Kaptai Project",
      "Kaptai Nuton Bazar",
      "Kaptai Sadar",
    ],
    Kawkhali: ["Betbunia", "Kalampati"],
    Khagrachari: [
      "Alichan Para",
      "Ananta Master Para",
      "Babuchhara",
      "Baghaichari Mukh",
      "Bara Panchhari",
      "Boalkhali Bazar",
      "Buddhist Monastery",
      "Chatrachhara Ch Mohan Para",
      "Chengy Square",
      "Dighinala",
      "Duluchhari",
      "Gyanangkur Buddha Vihara",
      "Islampur",
      "Jamtoli",
      "Jogesh Ch Karbari Para",
      "Kabakhali Bazar",
      "Khagrachari Sadar",
      "Komalchari Hadmanpara Bazar",
      "Kukichhara",
      "Lakshmichhari",
      "Logang",
      "Madhupur Bazar",
      "Madhya Dhanpatar",
      "Mahajanpara",
      "Mahalchhari",
      "Matiranga",
      "Narankhaya",
      "Nunchhari",
      "Panchhari",
      "Perachara",
      "Purbo Hasin Sanadpur",
      "Ramgarh",
      "Sardangchhara",
      "Shalbagan",
      "Shanirvar",
      "Taindang",
      "Thakurchara",
    ],
    "Khagrachari - Manikchhari": ["Manikchhari Sadar"],
    Kutubdia: ["Dhurung", "Kutubdia Sadar", "Lemsikhali"],
    Lakshmipur: [
      "Birahimpur Lakshmipur",
      "Charshai",
      "Jagannatpur",
      "Lakshmipur Sadar",
      "Lakshmipur Sadar Amani Lakshimpur",
      "Lakshmipur Sadar Chandraganj",
      "Lakshmipur Sadar Choupalli",
      "Lakshmipur Sadar Dalal Bazar",
      "Lakshmipur Sadar Duttapara",
      "Lakshmipur Sadar Keramatganj",
      "Lakshmipur Sadar Mandari",
      "Lakshmipur Sadar Rupchara",
    ],
    "Lakshmipur - Raipur": ["Keroa", "Raipur Sadar"],
    "Lakshmipur - Ramganj": [
      "Ramganj Alipur",
      "Ramganj Bazar",
      "Ramganj Dolta",
      "Ramganj Kanchanpur",
      "Ramganj Naagmud",
      "Ramganj Panpara",
    ],
    "Lakshmipur - Ramgati": [
      "Char Alexander",
      "Char Alexgander Hajirghat",
      "Char Goshai",
      "Char Poragacha",
      "Char Wapda",
      "Kamalnagar Jomidar Hat Bazar",
      "Ramgoti Bazar",
    ],
    Langadu: ["Gulshakhali", "Langadu Sadar"],
    Laxmichhari: ["Laxmichhari Sadar"],
    Lohagara: ["Lohagara Chunti", "Lohagara Lohagara", "Lohagara Padua"],
    Matiranga: ["Baranala", "Matiranga Sadar", "Taindong"],
    Mirsharai: [
      "Mirsharai Abutorab",
      "Mirsharai Azampur",
      "Mirsharai Bharawazhat",
      "Mirsharai Darrogahat",
      "Mirsharai Joarganj",
      "Mirsharai Korerhat",
      "Mirsharai Mirsharai",
      "Mirsharai Mohazanhat",
    ],
    Moheskhali: ["Gorakghat"],
    Naniachhar: ["Naniachhar Sadar"],
    Noakhali: [
      "Alayarpur",
      "Amishsha Para",
      "Andar Char",
      "Banglabazar",
      "Bangla Bazar",
      "Bashurhaat",
      "Binodpur",
      "Bishwanaath Bus Stop",
      "Bojra Bazar",
      "Boro Mosjid Mor",
      "Chaiyaani Bazar",
      "Chandraganj Bazar",
      "Char Elahi Bazar",
      "Char Jabbar",
      "Char Jublee",
      "Chatarpaiyaa",
      "Chatarpaiya Bazar",
      "Chatkil",
      "Chowmohani Chowrasta",
      "Church Of The Queen Of Lourdes",
      "Companiganj Noakhali",
      "Dotter Haat",
      "Ekhlashpur Bazar",
      "Eklashpur Bazar",
      "Gabua Bazar",
      "Gazirhat Bazar",
      "Harinarayanpur Railway Station",
      "Hatiya Upazila Parishad",
      "Housing State",
      "Islamganj Bazar",
      "Islamgonz Bazar",
      "Jomidar Haat",
      "Joyaag Bazar",
      "Kabirhaat",
      "Kalitera Bazar",
      "Kalyandi Post Office",
      "Kankirhaat",
      "Kashem Bazar",
      "Khalifar Hat Post Office",
      "Khaser Hat",
      "Kormulla Bazar",
      "Maijdee Bazar",
      "Mannan Nagar Bazar",
      "Master Para",
      "Medical Assistant Training School,Noakhali",
      "Mir Warishpur",
      "Mohila College Morr",
      "Molongchor Poler Gora",
      "Musapur Union Parishad",
      "Noakhali Bangla Bazar",
      "Noakhali Circuit House",
      "Noakhali Government College",
      "Noakhali Pouro Bazaar",
      "Noakhali Puraton College",
      "Noakhali Sadar Chaprashir Hat",
      "Noakhali Sadar Charam Tua",
      "Noakhali Sadar Char Jabbar",
      "Noakhali Sadar Din Monir Hat",
      "Noakhali Sadar Kabirhat",
      "Noakhali Sadar Khalifar Hat",
      "Noakhali Sadar Mriddarhat",
      "Noakhali Sadar Pak Kishoreganj",
      "Noakhali Super Market",
      "Noakhali Tv Center",
      "Noakhali Upazila Parishad",
      "Nowarhat Bazar",
      "NSTU",
      "Rajganj Post Office",
      "Ramjan Bibi",
      "Ramzanbibi Bazar",
      "Rongmala",
      "Sebarhat Bazaar",
      "Senbag",
      "Shaheber Haat",
      "Shetu Bhanga Bazaar",
      "Shubornochar",
      "Sonaimuri",
      "Sonapur Bus Stand",
      "Subarnachar Upazila Parishad",
      "Textile College",
      "Thekar Hat Bazar",
      "Totar Bazar",
      "Townhall Mor",
      "Trighoria",
    ],
    Panchhari: ["Panchhari Sadar"],
    Pashurampur: [
      "Pashurampur Fulgazi",
      "Pashurampur Munshirhat",
      "Pashurampur Pashurampur",
      "Pashurampur Shuarbazar",
    ],
    Patiya: ["Patiya Budhpara", "Patiya Sadar"],
    Rajsthali: ["Rajsthali Sadar"],
    Ramghar: ["Pathachhara", "Ramghar Head Office"],
    Ramu: ["Ramu Sadar", "Sonaichari"],
    "Rangamati Barkal": ["Barkal Bazar", "Barkal Sadar", "Panchagram"],
    "Rangamati Marishya": ["Marishya Sadar"],
    "Rangamati Town": [
      "Kathaltoli",
      "Manikchari Rangamati",
      "Rangamati Sadar",
      "Vedvedi",
    ],
    Rangunia: [
      "Dakkhin Ghatchak",
      "Fakirkill",
      "Kadeer Nagar",
      "Murad Nagar",
      "Rangunia Dhamair",
      "Rangunia Sadar",
      "Sayad Bari",
      "Uttar Gatchak",
    ],
    Raozan: [
      "Raozan B.I.T Post Office",
      "Raozan Beenajuri",
      "Raozan Dewanpur",
      "Raozan Fatepur",
      "Raozan Guzra Noapara",
      "Raozan jagannath Hat",
      "Raozan Kundeshwari",
      "Raozan Mohamuni",
      "Raozan Pouroshobha",
      "Rauzan Gahira",
    ],
    Raypur: [
      "Raypur Bhuabari",
      "Raypur Haydarganj",
      "Raypur Khaser Hat",
      "Raypur Nagerdighirpar",
      "Raypur Rakhallia",
      "Raypur Sadar",
    ],
    Sandwip: ["Sandwip Post Office", "Sandwip Shiberhat", "Sandwip Urirchar"],
    Satkania: [
      "Satkania Baitul Ijjat",
      "Satkania Bazalia",
      "Satkania Satkania",
    ],
    Senbag: [
      "Senbag Beezbag",
      "Senbag Chatarpaia",
      "Senbag Kallyandi",
      "Senbag Kankirhat",
      "Senbag Sadar",
      "Senbag T.P. Lamua",
    ],
    Shahrasti: [
      "Shahrasti Chotoshi",
      "Shahrasti Islamia Madrasha",
      "Shahrasti Khilabazar",
      "Shahrasti Pashchim Kherihar Al",
      "Shahrasti Sadar",
    ],
    Sitakunda: [
      "Sitakunda Barabkunda",
      "Sitakunda Baroidhala",
      "Sitakunda Bawashbaria",
      "Sitakunda Bhatiari",
      "Sitakunda Fouzdarhat",
      "Sitakunda Jafrabad",
      "Sitakunda Kumira",
      "Sitakunda Sitakunda",
    ],
    Sonagazi: [
      "Bakter Munshi Bazar",
      "Bara Ahmadpur",
      "Char Laxmiganj",
      "Miyar Bazar Post Office Maruar Char",
      "Motiganj",
      "Nababpur Bazar",
      "Nobi Ullah Bazar",
      "Olama Bazar",
      "Sombaria Bazar",
      "Sonagazi Ahmadpur",
      "Sonagazi Kazirhat",
      "Sonagazi Motiganj",
      "Sonagazi Sadar",
      "Sonagazi Upazila Office",
      "Sonapur Bazar",
      "Sulakhali",
      "Sundarpur Baligaon",
    ],
    Teknaf: ["Teknaf Hnila", "Teknaf Sadar", "Teknaf St.Martin"],
    Ukhia: ["Ukhia - Noapara", "Ukhia Sadar"],
  },
  Dhaka: {
    "Dhaka - North": [
      "Bashundhara R/A",
      "Abul Hotel Bus Stop",
      "Abur Tek Road",
      "ACS Garments (Ati Para)",
      "Adabor",
      "Adam Ali Market",
      "Adarsha Bag",
      "Aftab nagar",
      "Agargaon",
      "Ahmed Nagar",
      "Akij Foundation",
      "Al Huda Mosjid",
      "Ananda Nagar",
      "Apollo Hospital",
      "Arjat Para",
      "Ark Hospital",
      "Armanitola",
      "Army Society",
      "Army Stadium",
      "Asad Gate",
      "Ashalota",
      "Ashkona",
      "Ashkona Boro Mosjid",
      "Ashkona Dilder Bari",
      "Ashkona Mosjid Road",
      "Ashkona Panir Pamp",
      "Atipara Bazar",
      "Azompur Brac Market",
      "Badda",
      "Badda Hossain Market",
      "Bagbari",
      "Baily Road",
      "Baitul Azam Mosjid",
      "Balughat",
      "Banani Bus Stand",
      "Banani DOHS",
      "Banani Graveyard",
      "Banani Naval Head Quarter",
      "Banani Road No. 1 - 11",
      "Banani Road No. 12 - 19",
      "Banani Road No. 20 - 28",
      "Banasree Block A",
      "Banasree Block C",
      "Banasree Block D",
      "Banasree Block E",
      "Banasree Block J",
      "Banasree Block K",
      "Baridhara",
      "Baridhara DOHS",
      "Barontek",
      "Bashtola",
      "Bashundhara",
      "Bashundhara Block A",
      "Bashundhara Block B",
      "Bashundhara Block C",
      "Bashundhara Block D",
      "Bashundhara Block F",
      "Bashundhara Block H",
      "Bashundhara Block I",
      "Bashundhara Bus Stand",
      "Baunia",
      "Bawlia Para",
      "Bawneabad Area",
      "Begunbari",
      "Bepari Bari",
      "Bhuyia Para",
      "Bishteki",
      "Bonolota",
      "Borobagh",
      "Box Nagar",
      "CDH Shampan",
      "Chairman bari",
      "Chairman Para",
      "Chalabon",
      "Chamurkhan",
      "Chittagong Road",
      "City Complex Road",
      "Coca Cola Bus Stop",
      "Confidence Shopping Mall",
      "Darus Salam",
      "Dewan Bari",
      "Dewan City",
      "Dhaka - Cantonment",
      "Dhaka - North City Corporation Market",
      "Dhakinkhan Bazar",
      "Dhamrai",
      "Dhoronggar Tek",
      "Diabari",
      "Dobadia",
      "Doctor Goli",
      "Dokkhingao",
      "Dour",
      "East Hazipara",
      "East Merul Badda",
      "East Nakhalpara",
      "East Nurerchala",
      "East Rampura",
      "East West Medical College",
      "Faidabad Mor",
      "Faidabad Police Fari",
      "Faidabad Prmary School",
      "Farid Market",
      "Farmgate",
      "Gabtoli Bus Terminal",
      "Gawair",
      "Golartek",
      "Gono Koborshathan Road",
      "Goran Tampoo stand",
      "Gulshan 1",
      "Gulshan 2",
      "Gulshan Badda link Road",
      "Hatim Bag",
      "Hatirjheel",
      "Hazi Camp",
      "Helal Market",
      "Holan",
      "House Building",
      "Ibrahimpur",
      "ICDDRB",
      "IUBAT",
      "Jahangir Gate",
      "Jahurul Haque City",
      "Jamtola",
      "Jamuna Future Park",
      "Jashimuddin Road",
      "Joar Shahara",
      "Joynal Market",
      "Kacha Bazar",
      "Kachkura",
      "Kafrul",
      "Kalachandpur",
      "Kallyanpur",
      "Kamar Para",
      "Karwan Bazar",
      "Kathal tola",
      "Kawranbazar",
      "Kazi Bari",
      "Kazipara",
      "Khilgoan Bus stop",
      "Khilkhet",
      "Koloni Bazar",
      "Kosai Bazar",
      "Koshaibari",
      "Kunipara",
      "Kuril",
      "Kuril bus stop",
      "Kurmitola",
      "Malibag bus stand",
      "Malibag railgate",
      "Manikdi",
      "Master Para Bazar",
      "Masterpara Kola Bagan",
      "Master Para Munda",
      "Matikata",
      "Mazi Bari",
      "Medical Road",
      "Meradia",
      "Meradia Graveyeard",
      "Meradia kacha bazar",
      "Merul",
      "Miapara Mosjid Road",
      "Middle badda",
      "Middle Meradia",
      "Mirbag",
      "Mirpur 1",
      "Mirpur 10",
      "Mirpur 60 Feet",
      "Mirpur Botanical Garden",
      "Mirpur Cantonment",
      "Mirpur Ceramic",
      "Mirpur Colony",
      "Mirpur Darus Salam",
      "Mirpur DOHS",
      "Mirpur Govt Housing Estate",
      "Mirpur Kazipara",
      "Mirpur Rupnagar",
      "Mirpur Section 1",
      "Mirpur Section 11",
      "Mirpur Section 12",
      "Mirpur Section 13",
      "Mirpur Section 14",
      "Mirpur Section 15",
      "Mirpur Section 16",
      "Mirpur Section 2",
      "Mirpur Section 3",
      "Mirpur Section 4",
      "Mirpur Section 5",
      "Mirpur Section 6",
      "Mirpur Section 7",
      "Mirpur Section 8",
      "Mirpur Section 9",
      "Mirpur Shewrapara",
      "Mirpur Taltola",
      "Mirpur Zoo",
      "Modhubag",
      "Mohakhali",
      "Mohakhali Bus Stand",
      "Mohakhali DOHS",
      "Mohakhali Inter District Bus Terminal",
      "Mohakhali Kachabazar",
      "Mohakhali koraill Basti",
      "Mohakhali TB Gate Jame Mosjid",
      "Mohammadia Housing Limited",
      "Mohammadpur Chandmiya Housing",
      "Mohammadpur Mohammadia Housing Society",
      "Mohammadpur Mohammadia Non Housing Area",
      "Mohammadpur P C Culture Society",
      "Mohammadpur Residential Area",
      "Moinar Tek",
      "Mojibur Market",
      "Molla Para",
      "Mollartek",
      "Monipur",
      "Monipuri Para",
      "Mouchak Market",
      "Muktijoddha Road",
      "Munsi Market",
      "Nabisco Bus Stand",
      "Nadda",
      "Nagoria Bari",
      "Nakhalpara",
      "Nama Para",
      "Nasir er tek",
      "Neoyazbag",
      "Niketon",
      "Niketon Bazar gate",
      "Nikunja 1",
      "Nikunja 2",
      "Nishat Nagar",
      "Noddapara Club Mor",
      "Noddapara Mosjid Road",
      "Nogor Bari",
      "Nondipara",
      "Nondipara Bazar",
      "Nondoni Para",
      "Notunbag",
      "Notunbazar Bus Stand",
      "Noyatola",
      "Nurer Chala",
      "Paikpara",
      "Paschim Rampura",
      "Peyara Bagan",
      "Pink City",
      "Pirerbagh",
      "Police Plaza",
      "Prembagan",
      "Primary School",
      "Pular Tek",
      "Rajabari Mor",
      "Rajarbag Kalibari",
      "Ramjan Market",
      "Rampura Bazar",
      "Rampura Bus Stand",
      "Rana Vola",
      "Rasulbagh",
      "Rupali Garden",
      "Rupali Tower",
      "Satrasta",
      "Shahinbag",
      "Shahjahadpur Bus Stand",
      "Shahjahdpur",
      "Shamol Bagh",
      "Shantiniketon",
      "Shantipur",
      "Sharnalata",
      "Shena Maloncha",
      "Shenpara Parbata",
      "Sher-e-Bangla Nagar",
      "Shewrapara",
      "Shiddheshwari",
      "Shipahibag",
      "Shonirakhra",
      "Shyamoli",
      "Sipahi bag tampoo stand",
      "Solmaid",
      "Sona katra",
      "Sorkar Para",
      "South Badda",
      "South Banashree",
      "Subastu Nogorvally",
      "Taltola Khilgoan",
      "Taltola Mor",
      "Taltola Mosjid Road",
      "Tejgaon",
      "Tejgaon - Gulshan Link Road",
      "Tejgaon Industrial Area",
      "Tejkunipara",
      "Tek para",
      "Television Museum",
      "Tetul Tola",
      "Tibbet Factory",
      "TIC Colony Mor",
      "Tilpa Para",
      "Titas Road",
      "Transmitter Mor",
      "Trimohoni Bazar",
      "Trimohoni Bridge",
      "Truckstand",
      "Ulon",
      "Update Dental College",
      "Uttara Airport",
      "Uttara Ajompur",
      "Uttara Majar Road",
      "Uttara Sector 1",
      "Uttara Sector 10",
      "Uttara Sector 11",
      "Uttara Sector 12",
      "Uttara Sector 13",
      "Uttara Sector 14",
      "Uttara Sector 15",
      "Uttara Sector 2",
      "Uttara Sector 3",
      "Uttara Sector 4",
      "Uttara Sector 5",
      "Uttara Sector 6",
      "Uttara Sector 7",
      "Uttara Sector 8",
      "Uttara Sector 9",
      "Uttar Badda",
      "Uttargao",
      "Vashantek",
      "Vatara",
      "Vatara Mor",
      "West Hazipara",
      "West Nakhalpara",
      "West Rampura",
      "Wireless More Bus Stop",
    ],
    "Dhaka - South": [
      "New/Old Ak School",
      "Abdul Bani Road",
      "Abdul Hadi Lane",
      "Abed Dali Road",
      "Abhidas Lane",
      "Abul Hasnat Road",
      "Abul khairat Road",
      "Agamasi Lane",
      "Aga sadek road",
      "Ahmedbagh",
      "Ahsan Ullah Road",
      "Alamganj Road",
      "Al Amin Road",
      "Aminabad colony moghbaraz",
      "Aminbagh",
      "Anond mohan boshak Lane",
      "Arambagh",
      "Armenium Street",
      "Ashik lane",
      "Ayub Ali colony Rahim square",
      "Azimpur",
      "Azizullah Road",
      "Bagamganj Lane",
      "Bagdasa Lane",
      "Bahadurpur Lane",
      "Bailey Square Moghbazar",
      "Baitul Mukarram Stadium",
      "Bakshibagh",
      "Banasree",
      "Bandura Nawabganj",
      "Bangabandhu Avenue & Rest House",
      "Bangabhaban",
      "Bangladesh Bank Colony",
      "Bangladesh Railway Barracks",
      "Bangshal",
      "Bangshal Road",
      "Barnamala School",
      "Basabo",
      "Bashabo Ohaba Colony",
      "Bashir uddin road",
      "Bashundhara City",
      "Basu Bazar Lane",
      "BDR Pilkhana",
      "Begum Bazar",
      "Bhagwati Banerjee Road",
      "Bhanga Press",
      "Bhojhari Saha Street",
      "Bijoy Nagar",
      "Central prison",
      "central public library",
      "Chamelibagh",
      "Chandi Charan Bose Street",
      "Chankharpul lane",
      "Chan Para",
      "ChanPara Zia Bagh",
      "Chawk Bazar",
      "Chota Katra",
      "Circular Road",
      "Committee ganj",
      "Court House Street",
      "D.C Court",
      "Dayaganj Jelepara",
      "Dayaganj Road",
      "DC Roy Road",
      "Deen Nath Sen Road",
      "Demra",
      "Dhaka Cotton Mills",
      "Dhaka medical college",
      "Dhaka University",
      "Dhakeshwari Road",
      "Dhalpur",
      "Dhanmondi 1",
      "Dhanmondi 10",
      "Dhanmondi 10A",
      "Dhanmondi 11",
      "Dhanmondi 11A",
      "Dhanmondi 12",
      "Dhanmondi 12A",
      "Dhanmondi 13",
      "Dhanmondi 13A",
      "Dhanmondi 14",
      "Dhanmondi 15",
      "Dhanmondi 16",
      "Dhanmondi 17",
      "Dhanmondi 18",
      "Dhanmondi 19",
      "Dhanmondi 1A",
      "Dhanmondi 2",
      "Dhanmondi 20",
      "Dhanmondi 21",
      "Dhanmondi 22",
      "Dhanmondi 23",
      "Dhanmondi 24",
      "Dhanmondi 25",
      "Dhanmondi 26",
      "Dhanmondi 27",
      "Dhanmondi 28",
      "Dhanmondi 29",
      "Dhanmondi 2A",
      "Dhanmondi 3",
      "Dhanmondi 30",
      "Dhanmondi 31",
      "Dhanmondi 32",
      "Dhanmondi 3A",
      "Dhanmondi 4",
      "Dhanmondi 4A",
      "Dhanmondi 5",
      "Dhanmondi 5A",
      "Dhanmondi 6",
      "Dhanmondi 6A",
      "Dhanmondi 7",
      "Dhanmondi 7A",
      "Dhanmondi 8",
      "Dhanmondi 8A",
      "Dhanmondi 9",
      "Dhanmondi 9A",
      "Dhanmondi Staff Quarter",
      "Dholaipar",
      "Dilkusha",
      "Dilkusha Commercial Area",
      "Dr. M A Rashid Hall",
      "East Bashabo",
      "Eastern Housing",
      "East Raibazar",
      "Elephant Road",
      "Engineering University & Residential Area",
      "English Road",
      "Eskaton Garden Road",
      "Fakirapul",
      "Fakirapul Market Area",
      "Farashgang Lane",
      "Faridabad Lane",
      "Folder Street",
      "French Road",
      "Fulbaria Station East Area",
      "Ganguly Lane",
      "Gendaria",
      "Gendaria Rail Gate",
      "Ghaji Osman Gani Road",
      "Golakpal Lane",
      "Golam Mostafa Lane",
      "Gopibagh",
      "Gopinath Dutt Kabiraj Street",
      "Goran",
      "Govinda das lane",
      "Green corner green road",
      "Green Corner paribag",
      "Green Road East",
      "Green Road Staff Quarter",
      "Green Road West",
      "Green Square",
      "Gulbagh",
      "Gulistan",
      "Hafiz Ullah Road",
      "Haji Afsaruddin Road",
      "Haji Mohammad Moshin Hall",
      "Hakim Habibur Rahman Road",
      "Haricharan Roy Road",
      "Harish chand lane basu street",
      "Hari Street",
      "Hatembagh",
      "Hatirpool Free school Street",
      "Hatkhola Road",
      "Hazaribagh",
      "Hazi mainuddin Road",
      "High court Staff quarter",
      "Imam Gang",
      "Indrapuri",
      "Jagannath Hall",
      "Jatrabari",
      "Jatrabari Arot",
      "Jayakali Mandir Road",
      "Jhauchor",
      "Judge Court",
      "K.M Azam Lane",
      "K.Pk Ghosh Street",
      "Kadamtala",
      "Kadamtali",
      "Kajla",
      "Kakrail",
      "Kalabagan",
      "Kalabagan Free School Street",
      "Kalma Market",
      "Kamalapur",
      "Kamlapur",
      "Kamrangirchar",
      "Kanchpur",
      "Karimullarbagh",
      "Kasaituly",
      "Katherpul Lane",
      "Kazirbagh",
      "Kazi Zia uddin Lane",
      "Kedar Nath",
      "Khilgaon",
      "Khilgaon Bagicha",
      "Khilgaon Colony",
      "K M Das Lane",
      "Konapara",
      "Kutubkhali",
      "Kuwait friendship hospital",
      "Lalbagh",
      "Lalmatia",
      "Lal Mohan Poddar Lane",
      "Lalmohan Shah Street",
      "Large katra",
      "Madan Mohan Basak Road",
      "Madanshah Lane",
      "Madartek",
      "Madinabagh",
      "Malakartola Lane",
      "Malibag",
      "Malibagh Bazar Road",
      "Malitola lane",
      "Maniknagar",
      "Manik Nagar",
      "Manik Nagar Miyazan Lane",
      "Maradia",
      "Matuail",
      "Mayakanon",
      "Merajnagar",
      "Methorpotty",
      "Middle Bashabo",
      "Mill Barracks",
      "Mintu Road",
      "Mir Hazaribagh",
      "Mitali road",
      "Mitfort Road",
      "Mogbazar Circuit House Road",
      "Moghbazar",
      "Moghbazar TNT colony",
      "Mohhammadbagh",
      "Mohini Mohandas Lane",
      "Mokim Katara",
      "Momenbagh",
      "Motijheel",
      "Motijheel Colony",
      "Motijheel Commercial Area",
      "Mugda",
      "Mugdapara",
      "Mujahid Nagar",
      "Municipal Staff Quarter",
      "Munir Hossain Lane",
      "Muradpur",
      "Mymensingh lane",
      "Nabalka Mia lane",
      "Narinda Lane",
      "Narinda Road",
      "National Museum Quarter",
      "Naveen Chandra Gombasi Road",
      "Nawab Deori",
      "Nawab Katara",
      "Nawab Street",
      "Nayapalton",
      "Nazira Bazar Lane",
      "Nazrul Islam Hall",
      "Neki Deori",
      "New Eskaton Road",
      "New Jurain Alam Bagh",
      "New market",
      "Nilkhet Babupara",
      "Noor box Lane",
      "North Bashabo",
      "North Circular Road",
      "NorthEast Bashabo",
      "North Jatrabari",
      "North Mugdapara Deputy Colony",
      "North Rajarbagh",
      "North Road",
      "NorthWest Jatrabari",
      "Outer Circular Road",
      "Padmolochan Roy Lane",
      "Palamganj",
      "Pallabi",
      "Palton",
      "Paribagh Shah Sahib Road",
      "Patlakhan Lane",
      "Patuatuli Lane",
      "PG Hospital",
      "Poet Jasim Uddin Hall",
      "Police Hospital",
      "Postagola",
      "Postal Colony",
      "Purana Paltan GPO",
      "Purana Paltan Line",
      "Puran Dhaka - Islampur",
      "Puran Para",
      "Railway Hospital area",
      "Rajabagh Police Line",
      "Rajani Bose Lane",
      "Rajani Chowdhury Road",
      "Rajarbag Police Line",
      "Rakhal chandra bashak lane",
      "Ramna",
      "Rampura",
      "Rayerbagh",
      "Rishikosh Das Road",
      "R K Mission Road",
      "Roisnagar",
      "Rokaya Hall",
      "Rupa das lal lane",
      "Rupchan Lane",
      "Sabujbagh",
      "Saddam Market",
      "Saidabad",
      "Salimullah Hall",
      "Samaswada lane",
      "Sarulia",
      "Satish Sarkar Road",
      "Satmasjid Road",
      "Sayed hasan Ali Lane",
      "Secretariat Road",
      "Segun Bagicha",
      "Shahbagh",
      "Shaheed Memorial Hall",
      "Shahidbagh",
      "Shahidullah Hall",
      "Shahjahanpur",
      "Shahjahanpur Railway Colony",
      "Shah Shaheb Lane",
      "Shakhari Bazar Road",
      "Shakhari Nagar Lane",
      "Shampur",
      "Shamsun Nahar Hall",
      "Shantibagh",
      "Shantinagar",
      "Shantinagar Market Area",
      "Sharat chandra chakraborty lane",
      "Sharatgupta Road",
      "Shashibhushan Chaterjee Lane",
      "Sheikdi",
      "Sheikh Majibur Rahman Hall",
      "Sherabangla Hall",
      "Sher e Bangla Road",
      "Shukrabad",
      "Shurwardi Hall",
      "Siddheshwari Road",
      "Siddique bazar",
      "Siddique lane",
      "Simson Road",
      "Sir AF Rahman hall",
      "Sobhanbagh",
      "Sohidnagar",
      "Sonali Bank Colony",
      "South Bashabo",
      "SouthEast Jatrabari",
      "South Jatrabari",
      "South Khilgaon",
      "South Rajarbagh",
      "Surya Sen Hall",
      "Sutrapur",
      "Swamibagh Lane",
      "Swamibagh New Township",
      "Swarighat east",
      "T & T Colony",
      "Tallabag",
      "Tanuganj Lane",
      "Thakurdas Lane",
      "Tikatuli",
      "Tipu Sultan Road",
      "Titumir Hall",
      "Topkhana Road",
      "Toynbee Circular Road",
      "Walter Road",
      "Wapda Colony",
      "Wari",
      "Wari Street",
      "West Bashabo",
      "West End Street",
      "West fulbarai area",
      "West Jatrabari",
      "West Juraine",
      "West Malibag",
      "WHO Mission Road",
      "Wise Ghat Road",
      "Zahur Haque Hall",
      "Ziaur Rahman Hall",
    ],
    Faridpur: [
      "Alfadanga",
      "Alipur",
      "Ambikapur",
      "Ambikapur Board Office",
      "Atrashi Sadarpur",
      "Bagat Bazar",
      "Baitul Aman Housing Society",
      "Baitulaman Politecni",
      "Bakhunda",
      "Bhanga",
      "Bhashanchar",
      "Bil Mamudpur",
      "Boalmari",
      "Bodorpur",
      "C&B Ghat",
      "Charbhadrasan Upazila Faridpur",
      "Char Hazigonj Bazar",
      "Chorkomlapur",
      "Chunaghata",
      "Dhuldi Bazar",
      "Dhuldi Railgate",
      "Durgapur Faridpur",
      "Engineering College",
      "Faridpur New Bus Stand",
      "Faridpur New Market",
      "Faridpur Sadar",
      "Gojaria Bazar",
      "Goldangi Faridpur",
      "Hat Krishnapur",
      "Horishova",
      "Hotath Bazar",
      "Ishan Gopalpur",
      "Jhiltuli",
      "Kamarkhali",
      "Kanaipur",
      "Kanaipur Bazar",
      "Kanaipur Tetul Tala",
      "Khabaspur",
      "Khaleque Bazar",
      "Khalilpur Bazar",
      "Khusir Bazar Faridpur",
      "Kobirpur",
      "Komlapur",
      "Komorpur",
      "Krishi College",
      "Laler Mor",
      "Maligram Bhanga",
      "Mamudpur",
      "Medical",
      "Modhukhali Upozila Faridpur",
      "Mohammadpur Bazar",
      "Mohila Road",
      "Momin Khar Hat",
      "Munshibazar",
      "Nagarkanda Upazila Faridpur",
      "Niltuli",
      "Old Bus Stand",
      "Onather Mor",
      "Peyarpur Bazar",
      "Pirerchor Bhanga",
      "Poranpur Bazar Faridpur",
      "Puran Gazi Bari",
      "Sadarpur Upazila Faridpur",
      "Sadipur Bazar",
      "Saltha Upazila Faridpur",
      "Sovarampur",
      "Station Bazar",
      "Talma Bazar",
      "Tepakhola",
      "Vai Vai Bazar",
      "West Khabaspur Faridpur",
    ],
    Gazipur: [
      "Ahmed Nagor Chowrasta",
      "Ambag",
      "Ansar Academy",
      "Apex Footwear Factory",
      "Bagher Bazar",
      "Bahadurpur - Mowna Gazipur",
      "Bahawalpur College Chowrasta",
      "Barmi",
      "Bashon Thana Chowrasta",
      "Bason Sorok",
      "Boadmill",
      "Board Bazar",
      "BRRI",
      "Brtc Chowrasta",
      "Chanda Bus Stand",
      "Chanda Palli Bidyut",
      "Chandra Baroipara",
      "Chandra Kobirpur",
      "Chatar Bazar",
      "Chowrasta Baypass",
      "Chowrasta Telipara",
      "Chowrasta Warelessgate",
      "Colombia Garments",
      "Deger Chala Road",
      "Dhakkinan Joydebpur",
      "Dhakkin Chaybithi",
      "Dhaladia Bazar - Mowana Gazipur",
      "Dhirashom Joydebpur",
      "Dird Composit - Mowna Gazipur",
      "Dukan Par",
      "Epsha Gate - Mowna Gazipur",
      "Gazipur Bot Tola Auto Stand",
      "Gazipur Bscic",
      "Gazipur Caller Bazar",
      "Gazipur Palli Biddyut",
      "Gazipur Sadar",
      "Great Wall City",
      "Harikan Road",
      "Hazir Pukur",
      "Horinhati",
      "Hotapara",
      "Islam Garments",
      "Islamic University",
      "Jel khana",
      "Jorun",
      "Joydebpur Police Line",
      "Joydebpur Rail Gate",
      "Kadda Bazar",
      "Kaliakaar",
      "Kaliakoir Board Ghar Bazar",
      "Kaliakoir Chandra Bus Stand",
      "Kaliakoir Fulbaria",
      "Kaliganj",
      "Kamar Juri",
      "Kapashia Barishab",
      "Kapashia Bus Stand",
      "Kapashia Chandpur",
      "Kapashia Durgapur",
      "Kapashia Ghagotia",
      "Kapashia Karihata",
      "Kapashia Rayed",
      "Kapashia Sonmania",
      "Kapashia Tokh",
      "Kapasia Bazar",
      "Kapasia Chala Bazar",
      "Kashimpur",
      "Kashimpur Hatimara",
      "Konabari Bashtola",
      "Konabari Nawjor",
      "Konabari Palli Biddyut",
      "Konabri College Gate",
      "Kudusnagor - Nill Nagor",
      "Laxmipura",
      "LIDA Textile",
      "Mahona Bhabanipur",
      "Maleker Bari",
      "Maona Baro Topa",
      "Maona C and B Bazar",
      "Maona Chowrasta",
      "Maona Mc Bazar",
      "Maona Noyonpur Bazar",
      "Maona Soling Mor",
      "Masterbari - Mowna Gazipur",
      "Mazar Road Riad",
      "Member Bari",
      "Mirzapur - Mowna Gazipur",
      "Mogorkal - Doshtola",
      "Monipur Bazar",
      "Monnunagar",
      "Mouchak",
      "Mouchak Cha Bagan",
      "Mouchak Vannara",
      "National University",
      "Noyapara - Mowna Gazipur",
      "Open University",
      "Parijat",
      "Polagach Road",
      "Purabari - Mowna Gazipur",
      "Purbachal Stellmill Road",
      "Rajbari Math Joydebpur",
      "Rajendrapur",
      "Rajendrapur Cantonment",
      "Rotonpur Railway",
      "Salna - Mowna Gazipur",
      "Shafipur Bazar",
      "Shafipur Boroibari",
      "Shafipur Shinabaha Bazar",
      "Sharifpur Road",
      "Shimultoli Joydebpur",
      "Sign Board",
      "Sreepur",
      "Sreepur Amraid",
      "Sreepur Gosinga",
      "Sreepur Joinabazar",
      "Sreepur Kawraid",
      "Sreepur Rajabari",
      "Sreepur Telihati",
      "Uttor Chayabithi",
      "Vushir Mill",
      "Zirani",
      "Zora Pump",
    ],
    Gopalganj: [
      "Arpara",
      "Gopalganj Dhaka Dakkhin",
      "Gopalganj Sadar",
      "Gopalganj Sadar Ulpur",
      "Gopinathpur",
      "Kashiani",
      "Kashiani Ramdia College",
      "Kotalipara",
      "Maksudpur",
      "Malenga",
      "Manikher",
      "Ratoil",
      "Tungipara",
      "Vatiapara",
    ],
    Keraniganj: [
      "Abdullahpur Bazar",
      "Ati bazar",
      "Basundhara",
      "Dohar",
      "Ekuriya",
      "Hasnabad",
      "Kaligonj",
      "Keraniganj Sadar",
      "Kodomtoly",
      "Konakhola",
      "Konda",
      "Ramerkanda",
      "Rohitpur",
      "Stand Bazar",
      "Zinzira",
    ],
    Kishoreganj: [
      "Abdullahpur",
      "Ashutia Bazar",
      "Austagram Adampur",
      "Austagram Bangal Para",
      "Austagram Deoghar",
      "Austagram Kalma",
      "Austagram Kastul",
      "Austagram Khayerpur Abdullahpur",
      "Austagram Purba Austagram",
      "Bajitpur",
      "Bajitpur Baliadi",
      "Bajitpur Dighirpar",
      "Bajitpur Dilalpur",
      "Bajitpur Gazir Char",
      "Bajitpur Halimpur",
      "Bajitpur Hilachia",
      "Bajitpur Humaipur",
      "Bajitpur Kailag",
      "Bajitpur Maij Char",
      "Bajitpur Pirijpur",
      "Bajitpur Sarar Char",
      "Banagram Bazar",
      "Bawlai",
      "Beltoly Bazar",
      "Bhairab",
      "Bhairab Aganagar",
      "Bhairab Gazaria",
      "Bhairab Kalikaprashad",
      "Bhairab Sadekpur",
      "Bhairab Shibpur",
      "Bhairab Shimulkandi",
      "Bhairab Sreenagar",
      "Binnadi Bazar",
      "Binnati",
      "Borpul ar mor",
      "Boulai Bazar",
      "Chadurar Pool Putimari",
      "Chamraghat Bazar",
      "Chauddasata",
      "Dana Patuli",
      "Haruya",
      "Hossaindi Bazar",
      "Hossainpur Araibari",
      "Hossainpur Bazar",
      "Hossainpur Gobindapur",
      "Hossainpur Jirani",
      "Hossainpur Pumdi",
      "Hossainpur Sahedal",
      "Hossainpur Sidhla",
      "Hossenpur",
      "Itna Badla",
      "Itna Baribari",
      "Itna Chowganga",
      "Itna Dhanpur",
      "Itna Elongjuri",
      "Itna Gazipur",
      "Itna Joysiddi",
      "Itna Mrigha",
      "Itna Raituti",
      "Jalalpur Bazar",
      "Jamtola Bazar",
      "Jangalia Bazar",
      "Jasodal",
      "Josudal Syed Nazrul Islam Medical",
      "Joybangla Bazar",
      "Karimganj",
      "Karimganj Baragharia",
      "Karimganj Bazar",
      "Karimganj Dehunda",
      "Karimganj Gujadia",
      "Karimganj Gundhar",
      "Karimganj Jafarabad",
      "Karimganj Joyka",
      "Karimganj Kadir Jungle",
      "Karimganj Niamatpur",
      "Karimganj Noabad",
      "Karimganj Sutar Para",
      "Katiadi",
      "Katiadi Achmita",
      "Katiadi Banagram",
      "Katiadi Bazar",
      "Katiadi Chandpur",
      "Katiadi Gochhihata",
      "Katiadi Jalalpur",
      "Katiadi Kargaon",
      "Katiadi Luhajuri",
      "Katiadi Masua",
      "Katiadi Mumurdia",
      "Katiadi Shaha Dhulia",
      "Kawna Bazar",
      "Khilpara",
      "Kishoreganj Bottrish",
      "Kishoreganj Chamra Bandar",
      "Kishoreganj Sadar",
      "Kishoreganj Sadar S.Mills",
      "Kishorgonj Bazar",
      "Korsha Kariail",
      "Kuliarchar",
      "Kuliarchar Chhaysuti",
      "Kuliarchar Faridpur",
      "Kuliarchar Gubaria Abdullahpur",
      "Kuliarchar Osmanpur",
      "Kuliarchar Ramdi",
      "Kuliarchar Salua",
      "Latibabad",
      "Latibpur Bazar",
      "Mahinanda",
      "Maij Khapan",
      "Maria Industrial City",
      "Maria Union Parishad",
      "Mirzapur Bazar",
      "MIthamoin",
      "Mithamoin Boirati",
      "Mithamoin Dhaki",
      "Mithamoin Ghagra",
      "Mithamoin Katkhal",
      "Mithamoin Kewarjore",
      "Nandail Chourasta",
      "Nanuur Bazar",
      "Nikli Chhatirchar",
      "Nikli Dampara",
      "Nikli Gurue",
      "Nikli Jaraitala",
      "Nikli Karpasha",
      "Nikli Singpur",
      "Nilganj Bazar",
      "Nogua",
      "Ostagram",
      "Pakundia",
      "Pakundia Bazar",
      "Pakundia Burdia",
      "Pakundia Chandipasha",
      "Pakundia Char Faradi",
      "Pakundia Egarasindur",
      "Pakundia Hosendi",
      "Pakundia Jangalia",
      "Pakundia Narandi",
      "Pakundia Patuabhanga",
      "Pakundia Sukhia",
      "Patuabhanga Bazar",
      "Pulergaat Bazar",
      "Puran Thana Bazar",
      "Purbo Shoti Bari",
      "Sadulla Bazar",
      "Sararchar",
      "Sholakia",
      "Sholakia Area",
      "Tarail Damiha",
      "Tarail Dhala",
      "Tarail Digdair",
      "Tarail Jawar",
      "Tarail Rauti",
      "Tarail Sachail",
      "Tarail Talganga",
      "Tarial",
    ],
    Madaripur: [
      "Adampur",
      "Arial Khan Ferry Ghat",
      "Balairkandi",
      "Charmuguria",
      "Durgabordi",
      "Kalkini",
      "Kazibari",
      "Khakdi Bus Stand",
      "Kulpoddi Post Office",
      "Madaripur Bus Terminal",
      "Madaripur Police Station",
      "Madaripur Sadar",
      "Mostafapur",
      "Mostafapur Bus Stand",
      "Panchar",
      "Puran Bazar",
      "Rajoir",
      "Rajoir Khalia",
      "Sahabrampur",
      "Shibchar",
    ],
    "Manikganj - Shibloya": [
      "Shibloya Aricha",
      "Shibloya Shibaloy",
      "Shibloya Tewta",
      "Shibloya Uthli",
    ],
    "Manikganj - Singair": [
      "Singair Baira",
      "Singair Basta Stand",
      "Singair Joymantop",
      "Singair Sadar",
    ],
    "Manikganj - Town": [
      "Baliati",
      "Barangail",
      "Betila",
      "Beutha",
      "Dashora",
      "Dautiya",
      "Gheor",
      "Gilondo",
      "Gorpara",
      "Horirampur",
      "Joyra",
      "Kachari",
      "Mahadebpur",
      "Manikganj Bazar",
      "Manikganj Doulatpur",
      "Manikganj Sadar",
      "Noyadingi",
      "Purra",
      "Rajibpur",
      "Saturia",
      "Seutha",
      "Uchutia",
    ],
    "Munshiganj - Gajaria": [
      "Gajaria Hossendi",
      "Gajaria Rasulpur",
      "Gajaria Sadar",
      "Gazaria Anarpur",
      "Gazaria Char Decree",
      "Gazaria Jamaldi",
      "Gazaria Mirergaon",
    ],
    "Munshiganj - Lohajong": [
      "Lohajong",
      "Lohajong Gouragonj",
      "Lohajong Haldia SO",
      "Lohajong Haridia",
      "Lohajong Haridia DESO",
      "Lohajong Korhati",
      "Lohajong Madini Mandal",
      "Lohajong Medini Mandal EDSO",
      "Louhajang Atigaon",
      "Louhajang Bankhira",
      "Louhajang Dohori",
      "Louhajang Ghurduwr",
      "Louhajang Jhaputia",
      "Louhajang Kahetara",
      "Louhajang Kalma",
      "Louhajang Nagerhat Bazar",
      "Louhajang Pachaldia",
      "Louhajang Satgharia",
      "Louhajang Surpara",
      "Louhajang Vorakor",
    ],
    "Munshiganj - Sirajdikhan": [
      "Sirajdikhan",
      "Sirajdikhan Ichapur",
      "Sirajdikhan Kola",
      "Sirajdikhan Malkha Nagar",
      "Sirajdikhan Shekher Nagar",
    ],
    "Munshiganj - Town": [
      "Adhara",
      "Aparkati",
      "Autshahi",
      "Bagahia Kandi",
      "Baghia",
      "Baghra",
      "Bajrajugini",
      "Bajrozogini",
      "Baligao",
      "Bankaij",
      "Betkahat",
      "Bhaggyakul",
      "Chahida Bazar",
      "Char Masura",
      "Dewbhog Bazar",
      "Dighirpar",
      "Dogachi",
      "Dulihatta",
      "East Shillmandi",
      "Fultola",
      "Gonokpara",
      "Hasail",
      "Hashail Bazar",
      "Hashara",
      "Hatimara",
      "Idrakpur",
      "Jorpukur Par",
      "Kata Khali Bazar",
      "Khanka Dalalpara",
      "Kolapara",
      "Kumarbhog",
      "Kurmira",
      "Lalmiah Bazar",
      "Loharpool",
      "Maijpara",
      "Makahati",
      "Mirkadim",
      "Moddho Courtgoan",
      "Motukpur",
      "Munshiganj Bazar",
      "Munshiganj Notungaon",
      "Munshiganj Sadar Kathakhali",
      "Munshiganj Sadar Mirkadim",
      "Munshiganj Sadar Mukterpur",
      "Munshiganj Sadar Munshiganj Sadar",
      "Munshiganj Sadar Rikabibazar",
      "Nalbunya Kandi",
      "North Islampur",
      "Nuraitoli",
      "Panchgaon Bazar",
      "Panchgharia Kandi",
      "Parulpara",
      "Ponchosar",
      "Poschim Manikpur",
      "Pura",
      "Pura EDSO",
      "Rarikhal",
      "Rikabi Bazar",
      "Ronch Moddhopara",
      "Shilimpur",
      "Shipahipara",
      "Sirajdikhan Nimtola",
      "South Islampur",
      "Sreenagar",
      "Sreenagar Damla",
      "Sreenagar Dogachi Bazar",
      "Sreenagar Kolapara Bazar",
      "Sreenagar Pania",
      "Sreenagar Tontor",
      "Svarnagram",
      "Tangibari",
      "Tongibari",
      "Vaggyakul SO",
      "Zapta",
    ],
    Narayanganj: [
      "Araihazar",
      "Araihazar Gopaldi",
      "Baidder Bazar",
      "Baidder Bazar Bara Nagar",
      "Baidder Bazar Barodi",
      "Bandar",
      "Bandar BIDS",
      "Bandar D.C Mills",
      "Fatullah",
      "Fatullah Bazar",
      "Madanganj",
      "Narayanganj Sadar",
      "Nobiganj",
      "Rupganj",
      "Rupganj Bhulta",
      "Rupganj Kanchan",
      "Rupganj Murapara",
      "Rupganj Nagri",
      "Siddirganj Adamjeenagar",
      "Siddirganj LN Mills",
      "Siddirganj Siddirganj",
    ],
    Narsingdi: [
      "Basail",
      "Belabo",
      "Bilasdi",
      "Bot-Tola",
      "Brahmondi",
      "Charnagardi",
      "Char Sindhur",
      "Chinishpur",
      "Daspara",
      "Dogoria",
      "Ghorashal",
      "Ghorashal Bazar",
      "Goradia",
      "Grorashal Pran Factory",
      "Grorashal Sarkar Khana",
      "Hazupur",
      "Janata Jute Mile",
      "Kandapara",
      "Karimpur",
      "Kawriapara",
      "Madhabdi",
      "Monohordi",
      "Monohordi Hatirdia",
      "Monohordi Katabaria",
      "Narsingdi Bazar",
      "Narsingdi College",
      "Narsingdi Sadar",
      "Palash",
      "Panchdona",
      "Raypura",
      "Raypura Bazar Hasnabad",
      "Raypura Radhaganj bazar",
      "Saheprotab",
      "Salidha",
      "Sarkarkhana",
      "Satirpara",
      "Shibpur",
      "Shilmandi",
      "Songita",
      "Torowa",
      "UMC Jute Mills",
      "Velanagar",
    ],
    Nawabganj: ["Bandura", "Joypara", "Khanepur", "Sujapur"],
    "Rajbari - Baliakandi": ["Baliakandi", "Baliakandi Nalia"],
    "Rajbari - Pangsha": [
      "Pangsha Mrigibazar",
      "Pangsha Ramkol",
      "Pangsha Ratandia",
      "Pangsha Sadar",
    ],
    "Rajbari - Town": [
      "Aladipur",
      "Banibaha",
      "Bank Para",
      "Bash Hata",
      "Beradanga",
      "Bhabanipur",
      "Boro Laxmipur",
      "Choto Bridge Khankhanapur",
      "Dewan Para",
      "Doulodia Ghat",
      "Doulodia Rail Station",
      "Doulodia Sign Board",
      "Doulodia Union Boad",
      "Fire Service Goalanda",
      "Goalanda Hospital",
      "Goalanda Mor",
      "Goalanda Railgate",
      "Jomider Bridge",
      "Kazibadha",
      "Kazikanda",
      "Kenala Ghat",
      "Khanapur Notun Bazar",
      "Khankhanapur",
      "Kollanpur",
      "Lokkhikul",
      "Mallaguti Bridge Goalanda",
      "Matir Para",
      "Mondalpara",
      "Panna Chottor",
      "Puran Honisova",
      "Rajbari Bag Mara",
      "Rajbari Bazar",
      "Rajbari Binodpur",
      "Rajbari Boropul",
      "Rajbari Bscic",
      "Rajbari College Para",
      "Rajbari Gudar Bazar",
      "Rajbari Jailkhana",
      "Rajbari Jamtola",
      "Rajbari Jutemil",
      "Rajbari Notun Para",
      "Rajbari Police Line",
      "Rajbari Public Health",
      "Rajbari Railgate",
      "Rajbari Sadar",
      "Rajbari Sadar Goalanda",
      "Rajbari Sadar Hospital Road",
      "Rajbari Sadar Khankhanapur",
      "Rajbari Sreepur",
      "Rajbari Terminal",
      "Sajankanda",
      "Surjo Nagar",
      "Vagolpur",
    ],
    Savar: [
      "Ashulia Paragram",
      "Ashulia Tongabari",
      "Hemayetpur Jainabari",
      "Hemayetpur Shampur",
      "Hemayetpur Tatulzhora Mor",
      "Jahangirnagar University",
      "Kashem Cotton Mills",
      "Rajphulbaria",
      "Savar Akran Bazaar",
      "Savar Amin Bazar",
      "Savar Aralia Bazar Jame Mosjid",
      "Savar Ashulia Stand",
      "Savar Baipayl",
      "Savar Bank Colony",
      "Savar Bank Town",
      "Savar Baroipara",
      "Savar Basp",
      "Savar Boliarpur",
      "Savar Bus Stand",
      "Savar Cantonment",
      "Savar Canttonment",
      "Savar Chakrobarti Stand",
      "Savar Chandra Stand",
      "Savar Chapain Road",
      "Savar Charabag More",
      "Savar CRP",
      "Savar Dairy Farm",
      "Savar Dhamrai Thana",
      "Savar Dhulivita Stand",
      "Savar Enam Medical College",
      "Savar EPZ",
      "Savar Genda",
      "Savar Gonoshastaya Kendra",
      "Savar Hemayetpur",
      "Savar Jamgara",
      "Savar Kacha Bazar",
      "Savar Kalampur Bazar",
      "Savar Kalampur Bus Stand",
      "Savar Khagan Bazar",
      "Savar Nama Bazar",
      "Savar Narshinghapur",
      "Savar Nayarhat Stand",
      "Savar New Depz",
      "Savar Nishchintapur Stand",
      "Savar Nobinagar",
      "Savar Old Depz",
      "Savar Polli Biddyut",
      "Savar Radio Colony",
      "Savar Rajashon",
      "Savar Sadar",
      "Savar Sorkar Market",
      "Savar Sreepur Stand",
      "Savar Thana Stand",
      "Savar Zirabo",
      "Saver P.A.T.C",
    ],
    "Shariatpur - Naria": [
      "Naria Bhozeshwar",
      "Naria Gharisar",
      "Naria Kartikpur",
      "Naria Sadar",
      "Naria Upshi",
    ],
    "Shariatpur - Town": [
      "Bhedorganj",
      "Damudhya",
      "Dashatta",
      "Dhanuka Police Line",
      "Gosairhat",
      "Jajira",
      "Kagdi Bazar",
      "Palong Bazar",
      "Sakhipur",
      "Shariatpur Sadar",
      "Shariatpur Sadar Angaria",
      "Shariatpur Sadar Chikandi",
      "Tulasar",
    ],
    "Tangail - Basail": ["Bagil", "Basail Bazar", "Basail Sadar"],
    "Tangail - Bhuapur": ["Arjuna", "Bhuapur Sadar", "Nikrail"],
    "Tangail - Deldur": [
      "Delduar Elasin",
      "Delduar Hinga Nagar",
      "Delduar Jangalia",
      "Delduar Lowhati",
      "Delduar Patharail",
      "Delduar Saddar",
    ],
    "Tangail - Dhanbari": ["Baniajan", "Dhanbari Sadar", "Dhopakhali"],
    "Tangail - Ghatail": [
      "Ghatail D. Pakutia",
      "Ghatail Dhalapara",
      "Ghatail Lohani",
      "Ghatail Saddar",
      "Ghatail Zahidganj",
    ],
    "Tangail - Gopalpur": [
      "Gopalpur Chatutia",
      "Gopalpur Hemnagar",
      "Gopalpur Jhowail",
      "Gopalpur Saddar",
    ],
    "Tangail - Kalihati": [
      "Kalihati Ballabazar",
      "Kalihati Elinga",
      "Kalihati Kalihati",
      "Kalihati Nagarbari",
      "Kalihati Nagarbari SO",
      "Kalihati Nagbari",
      "Kalihati Palisha",
      "Kalihati Rajafair",
    ],
    "Tangail - Madhupur": [
      "Ausnara",
      "Madhupur",
      "Madhupur Dhobari",
      "Sholakuri",
    ],
    "Tangail - Mirzapur": [
      "Mirzapur Gorai",
      "Mirzapur Jarmuki",
      "Mirzapur M.C. College",
      "Mirzapur Mohera",
      "Mirzapur Saddar",
      "Mirzapur Warri paikpara",
    ],
    "Tangail - Nagarpur": [
      "Nagarpur Dhuburia",
      "Nagarpur Sadar",
      "Nagarpur Salimabad",
    ],
    "Tangail - Sakhipur": [
      "Dariapur",
      "Kalmegha",
      "Sakhipur Kochua",
      "Sakhipur Sadar",
    ],
    "Tangail - Town": [
      "Charabari",
      "Elanga",
      "Gala",
      "Jugni Bazar",
      "Kasil",
      "Potol Bazar",
      "Pugli",
      "Rosulpur",
      "Salimpur",
      "Soto Basail",
      "Tangail Sadar",
      "Tangail Sadar Kagmari",
      "Tangail Sadar Karatia",
      "Tangail Sadar Porabari",
      "Tangail Sadar Santosh",
      "Tarotiya",
      "Vaita",
      "Vatkora",
    ],
    Tongi: [
      "27 Bus Stand",
      "Arichpur",
      "Badham",
      "Besic-fokir market",
      "Besic industrial area",
      "Beximco",
      "Bonomala",
      "Boro bari",
      "Cherag Ali",
      "Dewra",
      "Gazipura",
      "International madical",
      "Jhinu market",
      "Mail gate",
      "Mirarbazar",
      "Mirash para",
      "Pagar",
      "Shilmoon",
      "Shinbari",
      "Targach",
      "Tongi bazar",
      "Tongi Bscic",
      "Tongi college gate",
      "Tongi Sadar",
      "Tongi Station Road",
    ],
  },
  Khulna: {
    Bagerhat: [
      "Bagerhat Feri Ghat",
      "Bagerhat Launch Terminal",
      "Bagerhat Sadar",
      "Barabaria",
      "Bhanganpar Bazar",
      "Chalna Ankorage",
      "Charkulia",
      "Chitalmari",
      "Dariala",
      "Fakirhat",
      "Foylahat",
      "Gourambha",
      "Kachua",
      "Kahalpur",
      "Khardwar",
      "Mansa",
      "Mollahat",
      "Mongla Port",
      "Moniganj",
      "Morrelganj",
      "Nagarkandi",
      "P.C College",
      "Pak Gangni",
      "Rampal",
      "Rangdia",
      "Rayenda",
      "Sannasi Bazar",
      "Satgombuj",
      "Sonarkola",
      "Sonatunia",
      "Telisatee",
    ],
    Chuadanga: [
      "Alamdanga",
      "Alukdia",
      "Andulbaria",
      "Chuadanga Boalmari",
      "Chuadanga P.T.I",
      "Chuadanga Sadar",
      "Damurhuda",
      "Darshana",
      "Dingedah",
      "Doulatganj",
      "Doulotdiar",
      "Gaid Ghat",
      "Hardi",
      "Hatikata Mor",
      "Hat Kalugonj",
      "Hazrahati",
      "Hoidarpur",
      "Joforpur",
      "Mominpur",
      "Munshiganj",
      "Nilmoniganj",
      "Nur Nagar",
      "Sath Gari Mor",
      "Sorojganj",
      "Subdia",
      "Valaipur",
    ],
    Jashore: [
      "Abhaynagar",
      "Bagachra",
      "Bagherpara",
      "Basundia",
      "Benapole",
      "Bhugilhat",
      "Chanchra",
      "Chougachha",
      "Churamankathi",
      "Gouranagar",
      "Jadabpur",
      "Jashore Airbach",
      "Jashore Cantonment",
      "Jashore - Noapara",
      "Jashore Sadar",
      "Jashore Upa - Shahar",
      "Jeshore Rajarhat",
      "Jhikargachha",
      "Keshobpur",
      "Monirampur",
      "Rupdia",
      "Sarsa",
    ],
    Jhenaidah: [
      "Dobila",
      "Ektarpur",
      "Harinakundu",
      "Hat gopalpur Bazar",
      "Jakaria",
      "Jhenaidah Cadet College",
      "Jhenaidah-Kaliganj",
      "Jhenaidah Sadar",
      "Kangshee",
      "Kotchandpur",
      "Maheshpur",
      "Mayadhorpur Village",
      "Naldanga",
      "Shailakupa",
    ],
    "Khulna - Aliapur": ["Alaipur Sadar", "Belphulia", "Rupsha"],
    "Khulna -Amadee": ["Amadee Sadar"],
    "Khulna - Batiaghat": ["Batiaghat Sadar", "Surkalee"],
    "Khulna - Chalna Bazar": ["Bajua", "Chalna Bazar Sadar", "Dakup", "Nalian"],
    "Khulna - Digalia": [
      "Chandni Mahal",
      "Digalia Sadar",
      "Gazirhat",
      "Ghoshghati",
      "Senhati",
    ],
    "Khulna - Dumuria": ["Chuknagar", "Magurkhali", "Shahpur", "Sorafpur"],
    "Khulna - Paikgachha": ["Kapilmoni", "Paikgachha Sadar"],
    "Khulna - Terokhada": ["Ajogora", "Barasat", "Terokhada Sadar"],
    "Khulna - Town": [
      "Atra Shilpa Area",
      "BIT Khulna",
      "Doulatpur",
      "Jahanabad Cantonment",
      "Khulna G.P.O",
      "Khulna Sadar",
      "Khulna Shipyard",
      "Khulna University",
      "Siramani",
      "Sonali Jute Mills",
    ],
    Kushtia: [
      "Bheramara Bazar",
      "Boro Bazer",
      "BRB Bscic Area",
      "Chorhas",
      "Housing",
      "Islamic University - Kushtia",
      "Khas mathurapur",
      "Khoksa",
      "Kumarkhali",
      "Kumarkhali Bazar",
      "Kushtia Mohini",
      "Kushtia Sadar",
      "Lahini Bot Toil",
      "Mirpur",
      "Mojompur",
      "Mongolbari Bazar",
      "Poradaho Bazer",
      "Singer Mor",
      "Taragunia",
      "Tri-Mohoni Bazar",
    ],
    Magura: ["Magura Sadar", "Mohammadpur", "Shalikha Upazila", "Sreepur Road"],
    Meherpur: [
      "Amjhupi Bazar",
      "Bajitpur Border",
      "Bamun Para",
      "Baribaka",
      "Boro Bazar",
      "Bosepara",
      "Buripota Border",
      "Chadbil Mor",
      "Gangni Bamundi",
      "Gangni Dhankhola",
      "Gangni Harbhanga",
      "Gangni Kasba",
      "Gangni Kumaridanga",
      "Gangni Manikdia",
      "Gangni Nittyanandapur",
      "Gangni Sadar",
      "Gopalpur",
      "Khan Para",
      "Kolar Mor",
      "Kulbaria Bazar",
      "Meherpur Bandar",
      "Meherpur Bus Stand Para",
      "Meherpur College Mor",
      "Meherpur Ghosh Para",
      "Meherpur Hospital Gate",
      "Meherpur Hotel Bazar",
      "Meherpur Jailkhana Para",
      "Meherpur Mollick Para",
      "Meherpur Post Office",
      "Meherpur Sadar",
      "Meherpur Stadium Para",
      "Meherpur Wapda Mor",
      "Mujib Nagar Complex",
      "Mujibnagar Dariapur",
      "Mujibnagar Gopalpur",
      "Mujibnagar Gourinagar Haat",
      "Mujibnagar Mohajanpur",
      "Mujibnagar Monakhali",
      "Mujibnagar Roshikpur",
      "Ujolpur",
    ],
    Narail: [
      "Adompur",
      "Aladatpur",
      "Awuriya",
      "Badha Ghat Mor",
      "Balarampur",
      "Baradia",
      "Bashgram Bazar",
      "Bharashula",
      "Bhawakhali",
      "Bishnupur",
      "Bolorampur",
      "Chamroli",
      "Circuit House Area",
      "Dokkhin Narail",
      "Doljitpur",
      "Dumurtola",
      "Durvazury",
      "Ghorakhali Bazar",
      "Ghorakhali Mor",
      "Gobra Bazar",
      "Gochar",
      "Gourinagar Haat",
      "Habakhali",
      "Harigara Bajar",
      "Hatbariya",
      "Hobokhali",
      "Itna",
      "Jogia",
      "Jurulia",
      "Kalia",
      "Kalia Bagdanga Narail",
      "Kalia Ballahati",
      "Kalia Bazar",
      "Kalia Benda",
      "Kalia Chhota Kalia Part",
      "Kalia Chorkhali",
      "Kalia Piroli",
      "Kalia Polbazzar",
      "Kalia Purulia",
      "Kalia Tona",
      "Laxmipasha",
      "Lohagara Amada",
      "Lohagara Bazar",
      "Lohagara Dighalia",
      "Lohagara Gobornada",
      "Lohagara Kamthana",
      "Lohagara Manikgonj Bazar",
      "Lohagara Naldi Bazar",
      "Lohagara Noagram",
      "Lohagara Nowapara",
      "Lohagora",
      "Loskorpur",
      "Maijpara Bazar",
      "Maizpara",
      "Mirapara Bazar",
      "Mithapur Bazar",
      "Mohish Khola",
      "Mohiskhola",
      "Mulia",
      "Naldi",
      "Naragati Gouripur Bazar Narail",
      "Naragati Kalabaria Boaliarcharpara",
      "Narail Batenga",
      "Narail Chowrasta",
      "Narail City College Mor",
      "Narail DC Office Mor",
      "Narail Durgapur",
      "Narail Gabtola",
      "Narail Kurigram",
      "Narail Madrasa Bazar",
      "Narail Puratan Terminal Area",
      "Narail Puraton Bridge",
      "Narail Rupganj Bazar",
      "Narail Sadar",
      "Narail Sitarampur",
      "Narail Terminal",
      "Nayanpur",
      "Nirali",
      "Nishinath Tola",
      "Ronda Purba Para",
      "Rotodanga",
      "Rupgonj Bazar",
      "Shahabad",
      "Sheikh Rasel Bridge Mor",
      "Shemakhali",
      "Singia",
      "Sitarampur",
      "S M Sultan Memorial Area",
      "Sm Sultan Mor",
      "Sorospur",
      "South Narail",
      "Subdhi Danga",
      "Tularampur",
      "Tularampur Bajar",
      "Vaduli Danga",
      "Vatiya",
      "Vorasula",
    ],
    Satkhira: [
      "Assasuni",
      "Baikari Union",
      "Bhomra Union",
      "Budhhat",
      "Buri Goalini",
      "Chanduria",
      "Debhata",
      "Dhulihar",
      "Gabura",
      "Ghona",
      "Jhaudanga",
      "Kalaroa",
      "Kuskhali",
      "Nalta Mubaroknagar",
      "Noornagar",
      "Patkelghata",
      "Ratanpur",
      "Satkhira Islamia Acc",
      "Satkhira Kaliganj",
      "Satkhira Sadar",
      "Shyamnagar",
      "Taala",
    ],
  },
  Mymensingh: {
    "Jamalpur - Dewangonj": ["Dewangonj Dewangonj S. Mills", "Dewangonj Sadar"],
    "Jamalpur - Islampur": [
      "Islampur Durmoot",
      "Islampur Gilabari",
      "Islampur Sadar",
    ],
    "Jamalpur - Madarganj": ["Madarganj Balijhuri", "Madarganj Sadar"],
    "Jamalpur - Malandah": [
      "Malandah Jamalpur",
      "Malandah Mahmoodpur",
      "Malandah Malancha",
      "Malandah Sadar",
    ],
    "Jamalpur - Shorishbari": [
      "Madarganj Adarvita",
      "Shorishabari Bausee",
      "Shorishabari Jagannath Ghat",
      "Shorishabari Jamuna Sar Karkhana",
      "Shorishabari Pingna",
      "Shorishabari Shorishabari",
    ],
    "Jamalpur - Town": [
      "Beltia",
      "Bhabki",
      "Charpolisha",
      "Jamalpur Bus Terminal",
      "Jamalpur Court",
      "Jamalpur Nandina",
      "Jamalpur Narundi",
      "Jamalpur Railway Station",
      "Jamalpur Sadar",
      "Jamalpur Shantinagar",
      "Khoshmahal",
      "Shekhervita",
      "Shihata",
    ],
    "Mymensingh - Gaforgaon": [
      "Gaforgaon Duttarbazar",
      "Gaforgaon Kandipara",
      "Gaforgaon Sadar",
      "Gaforgaon Shibganj",
      "Gaforgaon Usti",
    ],
    "Mymensingh - Gouripur": ["Gouripur Ramgopalpur", "Gouripur Sadar"],
    "Mymensingh - Haluaghat": [
      "Haluaghat Dhara",
      "Haluaghat Munshirhat",
      "Haluaghat Sadar",
    ],
    "Mymensingh - Isshwargonj": [
      "Isshwargonj Atharabari",
      "Isshwargonj Isshwargonj",
      "Isshwargonj Sohagi",
    ],
    "Mymensingh - Muktagacha": ["Bahenga", "Muktagachha Sadar", "Palgaon"],
    "Mymensingh - Nandail": ["Nandail Gangail", "Nandail Sadar"],
    "Mymensingh - Phulpur": [
      "Phulpur Beltia",
      "Phulpur Phulpur",
      "Phulpur Tarakanda",
    ],
    "Mymensingh - Town": [
      "Akua",
      "Bhaluka",
      "C.K. Gosh Road",
      "Chorpara Area",
      "Fulbaria Asim",
      "Maskanda Bypass",
      "Mymensingh Sadar",
      "Mymensingh Sadar Agriculture Universi",
      "Mymensingh Sadar Biddyaganj",
      "Mymensingh Sadar Kawatkhali",
      "Mymensingh Sadar Shombhuganj",
      "Mymensingh Zero Point",
      "Rahamatpur Engineering College",
      "Sankipara Jamtola Ses More",
      "Tarakanda Bazar",
      "Trishal Kabi Nazrul University",
    ],
    "Mymensingh - Trishal": [
      "Trishal Ahmadbad",
      "Trishal Dhala",
      "Trishal Ram Amritaganj",
      "Trishal Saddar",
    ],
    Netrokona: [
      "Atpara",
      "Barhatta",
      "Dharmapasha",
      "Dhobaura",
      "Dhobaura Sakoai",
      "Kalmakanda",
      "Kendua",
      "Khaliajuri Saddar",
      "Khaliajuri Shaldigha",
      "Madan Madan",
      "Moddhynagar Moddoynagar",
      "Mohanganj",
      "Netrakona Sadar",
      "Netrakona Sadar Baikherhati",
      "Pachkahonia",
      "Purbadhola Jaria Jhanjhail",
      "Purbadhola Saddar",
      "Purbadhola Shamgonj",
      "Susung Durgapur",
    ],
    Sherpur: [
      "Akheri Bazar",
      "Astomi Tola",
      "Bakshigonj Bakshigonj",
      "Bazit Khila",
      "Boira Puran Pur",
      "Chakpathak",
      "Chapatoli",
      "Chowrasta More",
      "Dhakolhati",
      "Durga Narayan Pur",
      "Garial Bari",
      "Gouripur",
      "Gowalpotti",
      "Gridda Narayanpur",
      "Jhinaigati",
      "Khowarpar",
      "Kushum Hati",
      "Methor Potti",
      "Moddho Sheri",
      "Nabaron School",
      "Nakla",
      "Nakla Gonopaddi",
      "Nalitabari",
      "Nalitabari Hatibandha",
      "Nayanibazar",
      "Nazira Bag Bazar",
      "Puraton Goru Hati",
      "Rajbollobpur",
      "Rangmahal",
      "Rogunath Bazar",
      "Shajbor Khila",
      "Shekh Hati",
      "Sheri Bridge",
      "Sherpur Bagbari",
      "Sherpur Bot Tola",
      "Sherpur College Mor",
      "Sherpur Jailkhana Mor",
      "Sherpur Kalibari",
      "Sherpur Kaliganj",
      "Sherpur Kasba",
      "Sherpur Mirganj",
      "Sherpur New Market",
      "Sherpur Nobinagar",
      "Sherpur Nowhata",
      "Sherpur Sadar Hospital",
      "Sherpur Shadar",
      "Sherpur Thana Mor",
      "Sherpur Truck Station",
      "Sherpur Wireless Mor",
      "Shib Bari",
      "Shingpara",
      "Shitolpur",
      "Shribardi Shribardi",
    ],
  },
  Rajshahi: {
    Bogura: [
      "Adamdighi",
      "Bagura Cantonment",
      "Bagura Sadar",
      "Balkuchi",
      "Balukapara",
      "Barachapra",
      "Bottola Bazar",
      "Chalapara",
      "Champapur",
      "Chandaikona",
      "Chandan Baisha",
      "Chhantiagram",
      "Debkhanda",
      "Dhunat",
      "Dupchachia",
      "Erulia",
      "Gabtoli",
      "Gokul",
      "Gosaibari",
      "Goshaibari",
      "Kahaloo",
      "Kahalu",
      "Khanpur",
      "Koyel",
      "Kundagram",
      "Kutubpur",
      "Lahiri Para",
      "Namuja",
      "Nandigram",
      "Nasharatpur",
      "Nasratpur",
      "Noongola",
      "Palli Unnyan Accademy",
      "Santahar",
      "Santahar Pouroshova",
      "Sariakandi",
      "Shabgram",
      "Shalikha",
      "Shekharkola",
      "Sherpur",
      "Sherpur Chakatola Road",
      "Shibganj",
      "Sonatola",
      "Sukhanpukur",
      "Talora",
      "Ulipurpara",
      "Utra",
    ],
    "Chapai Nawabganj": [
      "Amnura",
      "Bholahat",
      "Chapai Nawabganj Sadar",
      "Char Bagdanga",
      "Debinagar",
      "Gobratola",
      "Gomashtapur",
      "Kansart",
      "Manaksha",
      "Mandumala",
      "Moharajpur",
      "Nachol",
      "Rajarampur",
      "Ramchandrapur",
      "Rohanpur",
      "Shahibag",
      "Shibganj U.P.O",
    ],
    Joypurhat: [
      "Akklepur",
      "Amdai",
      "Bhadsha Union",
      "Dhalahar",
      "Jamalganj Bazar",
      "Joypurhat Municipality Office",
      "Joypurhat Sadar",
      "Joypurhat Stadium",
      "Kalai",
      "Khetlal",
      "Mongolbari",
      "Panchbibi",
      "Puranapail",
      "Tilakpur",
    ],
    Naogaon: [
      "Ahsanganj",
      "Badalgachhi",
      "Balihar",
      "Baludanga",
      "Bandai",
      "Dhamuirhat",
      "Dubalhati",
      "Hashaighari",
      "Kashimpur Bazar",
      "Mahadevpur",
      "Manda",
      "Moduhil",
      "Naogaon Sadar",
      "Niamatpur",
      "Nitpur",
      "Panguria",
      "Patnitala",
      "Porsa",
      "Prasadpur",
      "Raninagar",
      "Sailgachhi",
      "Sapahar",
    ],
    Natore: [
      "Abdulpur",
      "Baiddyabal Gharia",
      "Baraigram",
      "Dattapara Bazar",
      "Dayarampur",
      "Digapatia",
      "Gopalpur U.P.O",
      "Harua",
      "Hatgurudaspur",
      "Lalpur S.O",
      "Laxman",
      "Madhnagar",
      "Natore Sadar",
      "Singra",
    ],
    Pabna: [
      "Banwarinagar",
      "Bera",
      "Bhangura",
      "Chatmohar",
      "Dashuria",
      "Debottar",
      "Dhapari",
      "Hamayetpur",
      "Ishwardi",
      "Kaliko Cotton Mills",
      "Kashinathpur",
      "Nakalia",
      "Pabna Sadar",
      "Pakshi",
      "Puran Bharenga",
      "Rajapur Bus Station",
      "Ruppur",
      "Sagarkandi",
      "Sathia",
      "Sujanagar",
    ],
    Rajshahi: [
      "Arani",
      "Bagha",
      "Bhabaniganj",
      "Bhatkandi",
      "Binodpur Bazar",
      "Charghat",
      "Durgapur",
      "Ghoramara",
      "Godagari",
      "Katakhali",
      "Kazla",
      "Khodmohanpur",
      "Lalitganj",
      "Nowhata",
      "Premtoli",
      "Putia",
      "Rajshahi Cantonment",
      "Rajshahi Court",
      "Rajshahi Sadar",
      "Rajshahi Sugar Mills",
      "Rajshahi University",
      "Sapura",
      "Sardah",
      "Shyampur",
      "Taherpur",
      "Tanor",
    ],
    Sirajganj: [
      "Baiddya Jam Toil",
      "Belkuchi",
      "Dhangora",
      "Enayetpur",
      "Gandail",
      "Jamirta",
      "Kaijuri",
      "Kazipur",
      "Lahiri Mohanpur",
      "Makimpur",
      "Malonga",
      "Porjana",
      "Raipur Station Playground",
      "Rashidabad",
      "Salap",
      "Shahjadpur",
      "Shuvgachha",
      "Sirajganj Sadar",
      "Sohagpur",
      "Sthal",
      "Tarash",
      "Ullapara",
      "Ullapara R.S",
    ],
  },
  Rangpur: {
    Dinajpur: [
      "Ambari Bazar",
      "Ansar Club",
      "Asrom Para",
      "Bahadur Bazar",
      "Barapukuria Koylakhoni",
      "Basuniya Potti",
      "Bekipul",
      "BGB Camp",
      "Bhushir Bandar",
      "Birampur",
      "Birol",
      "Birol Bazar",
      "BKSP",
      "Bocaganj",
      "Boro Gurgola",
      "Boromath",
      "Botibabur Mor",
      "Bottoli Bazar",
      "Bottoli Mor",
      "Brac Center",
      "Brtc Road",
      "Chak Banarasi",
      "Charubabur More",
      "Chawliya Potti",
      "Chehelgazi School",
      "Chirir Bandar",
      "Chok Bazar",
      "Choto Gurgola",
      "Chourangi Mor",
      "Churipotti Mor",
      "Dabgach Mosque",
      "Dailar Mor",
      "Dc Office",
      "Dinajpur Bus Terminal",
      "Dinajpur Circuit House",
      "Dinajpur Education Board",
      "Dinajpur - Golapganj",
      "Dinajpur Govt. College",
      "Dinajpur Palli Biddyut",
      "Dinajpur Sadar",
      "Dinajpur Technical Training Centre",
      "Dinajpur Upazila Gate",
      "Dinajpur Women Govt. College",
      "Doshmile",
      "Fakir Para",
      "Foridpur Gorsthan",
      "Fulbari",
      "Fultola Bazar",
      "Gabura Bridge",
      "Gaocia Gaerege Mor",
      "Garments Bazar",
      "Gausul Azom Eye Hospital",
      "Ghasipara",
      "Ghoraghat",
      "Golapbag",
      "Goneshtola",
      "Gopalgonj Bazar",
      "Gunjabari",
      "Hili Hakimpur",
      "Holy Land College",
      "Holy Land Women Campus",
      "Hospital Mor",
      "Housing Mor",
      "Indra Mor",
      "Iqbal School Mor",
      "Islami Hospital",
      "Jail Road",
      "Jamtoli Bazar",
      "Jorabridge",
      "Kalur Mor",
      "Kana Hafez Mor",
      "Kanchon Bridge Mor",
      "KBM College",
      "Khaharol",
      "Khal Para",
      "Khanpur Bodar",
      "Khansama",
      "Khetripara",
      "Khokon Mowlovi Mor",
      "Kholahati Cantorment",
      "Kisan Bazar",
      "Kobiraj Hat",
      "Komolpur",
      "Kosba",
      "Kutubdanga Bazzar",
      "Labur Mor",
      "Lalbag Mor",
      "Law College Mor",
      "Maldahpotti",
      "Mamun Mor",
      "Masimpur",
      "Matasagor",
      "Medical College",
      "Mission Road",
      "Misson Get",
      "Mohanpur",
      "Mohonpur Rabar Dam",
      "Monggolpur",
      "Mushipara Jail Road",
      "Nabil Counter",
      "Nawabganj",
      "New Town 1",
      "New Town 2",
      "New Town 3",
      "New Town 4",
      "New Town 5",
      "Newtown 6",
      "Newtown 7",
      "Newtown 8",
      "Nimtola",
      "Notun Para",
      "Noyanpur",
      "Paglamor",
      "Paharpur",
      "Paker Hat",
      "Patua Para",
      "Police Line Market",
      "Polytechnical College",
      "Professor Para",
      "PTI Mor",
      "Rab -13 Camp",
      "Rail Bazar",
      "Rajbati",
      "Ramdubi Hat",
      "Ramnogor",
      "Ramsagor",
      "Raniganj Bazar",
      "Ranirbandar",
      "Sekhpura",
      "Setabganj",
      "Sikdar Hat",
      "Sohid Minar Mor",
      "Sostitola",
      "Staf Quarter Mor",
      "Station Road",
      "Tap Biddyut Kendro",
      "Thana Mor",
      "Tnt Mor",
      "Zia Heart Foundation",
    ],
    Gaibandha: [
      "Ambari",
      "Badiakhali",
      "Baghjana",
      "Balashi Ghat",
      "Bara Gayaspur",
      "Bisramgachi",
      "Chandipur",
      "Fulchari Konchi Para",
      "Gaibandha Sadar",
      "Gobindaganj Baluyapara",
      "Gobindaganj Mollapara",
      "Gobindoganj",
      "Indira Par",
      "Jalinge",
      "Jugibai",
      "Kanipara",
      "Kumarpara",
      "Kuptola",
      "Masterpara",
      "Modhdhopara",
      "Mondolpara",
      "Nawabganj Pholia",
      "Palashbari",
      "Polash Para",
      "Sadullapur",
      "Sadullapur Naldanga Union",
      "Saghata Bonapara Bazar",
      "Suigram",
      "Sundarganj",
    ],
    Kurigram: [
      "Bhogdanga",
      "Bhurungamari",
      "Char Rajibpur",
      "Chilmari",
      "Jatrapur",
      "Kurigram Phulbari",
      "Kurigram Rajarhat",
      "Kurigram Sadar",
      "Nageshwari",
      "Panchgachi",
      "Rangalirbash",
      "Rowmari",
      "Ulipur",
    ],
    Lalmonirhat: [
      "Aditmari Bhelabari",
      "Aditmari Durgapur",
      "Aditmari Kamlabari",
      "Aditmari Kashiabarir Hat",
      "Aditmari Mohiskhocha",
      "Aditmari Polashi",
      "Aditmari Saptipari Bazar",
      "Aditmari Sarpukur",
      "Aditmari Upazila Parishad",
      "Balatari Jame Mashjid Lalmonirhat",
      "Barabari",
      "Circuit House Lalmonirhat",
      "Hatibandha Barakhata",
      "Hatibandha Dauabari",
      "Hatibandha Goddimari",
      "Hatibandha Gotamari",
      "Hatibandha Shinduna",
      "Kaliganj Bhotmari",
      "Kaliganj Chandrapur",
      "Kaliganj Dalagram",
      "Kaliganj Gorol",
      "Kaliganj Kakina",
      "Kaliganj Modati",
      "Kaliganj Tushvandar",
      "Kaliganj Vullar Hat",
      "Lalmonirhat Sadar",
      "Lalmonirhat Stadium Road",
      "Noyar hat",
      "Patgram Baura",
      "Patgram Burimari",
      "Patgram Jongra",
      "Patgram Kawamari Bazar",
      "Patgram Kuchlibari",
      "Patgram Munshir Hat",
      "Patgram Sreerampur",
      "Patgram Thana",
    ],
    Nilphamari: [
      "Badia'r Mor",
      "Chowrongi Mor",
      "Circuit House Mor",
      "College Station",
      "Dimla Balapara",
      "Dimla Gayabari",
      "Dimla Khoga Khoribari",
      "Dimla Nautara",
      "Dimla Paschim Chatnai",
      "Dimla Sadar",
      "Dimla Shothibari Bazar",
      "Domar Boragari Bazar",
      "Domar Gomnati Bazar",
      "Domar Halhalia",
      "Domar Sonaray Bazar",
      "Domar Thana",
      "Harowa",
      "Kalitola",
      "Kishoreganj Check Post Bazar",
      "Kishoreganj Kalikapur",
      "Maniker Mor",
      "Nilphamari - Gobindopur",
      "Niphamari Kishoreganj Sadar",
      "Notkhana",
      "Pouro Market",
      "Railway Station",
    ],
    "Nilphamari - Saidpur": [
      "Bangalipur",
      "Cant Bazar",
      "Golahat Railway Colony",
      "Hati Kahana",
      "Kashiram Belpukur",
      "Kundol",
      "Nilphamari Sadar",
      "Saidpur Airport",
      "Saidpur Bus Terminal",
      "Saidpur Lakshmanpur",
      "Saidpur Pach Matha Mor",
      "Saidpur Plaza",
      "Saidpur Post Office",
      "Saidpur Railway Station",
      "Saidpur Super Market",
      "Wapda Bazar",
    ],
    Panchagarh: [
      "Atwari",
      "Boda Banagram",
      "Boda Haldibari",
      "Boda Maidandighi",
      "Bp Government High School Hostel Panchagarh",
      "Debigang Thana",
      "Debiganj Dhuajhari Bazar",
      "Debiganj Kaharganj",
      "Docropara",
      "Nimnagar Mosque Panchagarh",
      "Panchagarh Sadar",
      "Tetulia",
    ],
    Rangpur: [
      "Adarsopara",
      "Alamnagar Road",
      "Ansari Mor",
      "Arshad Nagor",
      "Asrotpur",
      "Babukha",
      "Badarganj",
      "Badarganj Sahidminar",
      "Bangladesh Bank Mor",
      "Barabil Gangachara",
      "Beacon Mor",
      "Betpotti",
      "Birganj",
      "Boiragi Para",
      "Bokultola",
      "Borobari",
      "Boubazar",
      "Burirhat",
      "C.M.B Quarter",
      "C.O Bazar",
      "Central Road",
      "Charokbari",
      "Chartola Mor",
      "Chatra",
      "Checkpost 3 Numbar",
      "Chirirbandar",
      "Chokbazar",
      "Circuit House Lane",
      "City Bazar",
      "D.C Mor",
      "Deodoba",
      "Dhap Engineer Para",
      "Dhaperhut Palichara",
      "Dhap Haji Para",
      "Dhap Masterpara",
      "Dhap Sagor Para",
      "Dhap Sardar Para",
      "Dharsona",
      "Dr. Wazed Miah Textile Engineering College",
      "Gamostopara",
      "Ghunjonmor",
      "Gl Roy Road",
      "Gonespur",
      "Grand Hotel Mor",
      "Guptopara",
      "Gurati Para",
      "Habibnagar Akhalitari",
      "Hanumantola",
      "Haragach",
      "Horidebpur",
      "Indrarmore",
      "Jaldhaka Nilphamari",
      "Jalkor",
      "Jummapara",
      "Jummapara Pakarmatha",
      "Kachari Bazar",
      "Kaharole",
      "Kakoli Lane",
      "Kamalkachna",
      "Kamarpara",
      "Karuponno Alamnagor",
      "Katki Para",
      "Kaunia",
      "Kellaband",
      "Kerani Para",
      "Khamar Mor",
      "Khasbag",
      "Kobaru",
      "Kukrul Golakatamor",
      "Lalkuti Lane",
      "Lohaqusi Shukurer Hat",
      "Madarganj",
      "Mahigonj",
      "Medical Pakarmatha",
      "Medical Purbo Gate",
      "Medical Quater",
      "Milonpara",
      "Mithapukur",
      "Mohadevpur",
      "Mondol Para",
      "Mordern",
      "Mulatol",
      "Munsipara",
      "Nazirrerhat",
      "New Jummapara",
      "New Shahebganj",
      "Nil Kantho",
      "Nisbedganj",
      "Noyatola Saidpur",
      "Nurpur",
      "Paglapir",
      "Pairaband",
      "Palpara",
      "Parkmor",
      "Pasari Para",
      "Payra Chattar",
      "Pirgacha",
      "Pirganj",
      "Pirpur",
      "Pouro Bazar",
      "Poyradanga Nageswari",
      "Press Club",
      "Prime Medical",
      "Radhaballav",
      "Rail Station",
      "Ramchandrapur Bazar",
      "Rangpur Cadet College",
      "Rangpur Cantontment",
      "Rangpur Medical Pakar Matha",
      "Rangpur Sadar",
      "Raypur",
      "Rcc Mor",
      "Rfl Foundary",
      "RK Road",
      "Robertsongonj",
      "Salbon Mistripara",
      "Sardarpara",
      "Satmatha",
      "Senpara",
      "Shampur Road",
      "Shapla",
      "Shayamoli Lane",
      "Shimulbag",
      "Shukurer Hat",
      "Siyalurmor",
      "Sultanmor",
      "Super Market",
      "Tajhat",
      "Taraganj",
      "Tati Para",
      "Thikadarpara",
      "Uttom Hajirhat",
      "Vogi Lane",
    ],
    Thakurgaon: [
      "BADC Staff Quarter",
      "Baliadangi",
      "Baliadangi Ruhia",
      "Border Guard Bangladesh",
      "College Para",
      "Goalpara",
      "Gobindo Nogor Mondir Para",
      "Goreya",
      "Goshpara",
      "Hazipara",
      "Islambag",
      "Jamidarpara",
      "Kalitola Bazar",
      "Khalpara",
      "Nishchintapur",
      "Ranisankail Durlovpur",
      "Ranisankail Mirdangi",
      "Ranisankail Rajbari",
      "Sarakar Para",
      "Thakurgaon - Haripur",
      "Thakurgaon - Munshipara",
      "Thakurgaon - Pirganj",
      "Thakurgaon Sadar",
      "Thakurgaon - Tatipara",
    ],
  },
  Sylhet: {
    Balaganj: [
      "Balaganj Begumpur",
      "Balaganj Brahman Shashon",
      "Balaganj Gaharpur",
      "Balaganj Goala Bazar",
      "Balaganj Karua",
      "Balaganj Kathal Khair",
      "Balaganj Natun Bazar",
      "Balaganj Omarpur",
      "Balaganj Sadar",
      "Balaganj Tajpur",
    ],
    Bianibazar: [
      "Beanibazar Beanibazar",
      "Beanibazar Churkai",
      "Beanibazar jaldup",
      "Beanibazar Kurar bazar",
      "Beanibazar Mathiura",
      "Bianibazar Salia bazar",
    ],
    Bishwanath: [
      "Bishwanath Bishwanath",
      "Bishwanath Dashghar",
      "Bishwanath Deokalas",
      "Bishwanath Doulathpur",
      "Bishwanath Singer kanch",
    ],
    Fenchuganj: [
      "Dowbangla",
      "Fenchuganj Fenchuganj",
      "Fenchuganj Fenchuganj SareKarkh",
    ],
    Goainhat: ["Goainhat Chiknagul", "Goainhat Goainhat", "Goainhat Jaflong"],
    Golapganj: [
      "Banigram",
      "Bhadeshwar",
      "Budhbari Bazar",
      "Dhaka Dakkhin",
      "Golapganj Sadar",
      "Jalalpur",
      "Kotalpur",
      "Ranaping Bazar",
      "Shekhpur",
      "West Barokut",
    ],
    Habiganj: [
      "Azmireeganj",
      "Bahubal",
      "Baniachang",
      "Baniachang Jatrapasha",
      "Baniachang Kadirganj",
      "Chunarughat",
      "Chunarughat Chandpurbagan",
      "Chunarughat Narapati",
      "Habiganj Sadar",
      "Habiganj Sadar Gopaya",
      "Habiganj Sadar Shaestaganj",
      "Madhabpur",
      "Madhabpur Itakhola",
      "Madhabpur Saihamnagar",
      "Madhabpur Shahajibazar",
      "Nabiganj",
      "Nabiganj Digalbak",
      "Nabiganj Golduba",
      "Nabiganj Goplarbazar",
      "Nabiganj Inathganj",
      "Shaestaganj Gonganagar",
      "Sheaestaganj Shankhola Bazar",
    ],
    Jakiganj: ["Zakiganj Bazar", "Zakiganj Ichhamati", "Zakiganj Sadar"],
    Kanaighat: [
      "Kanaighat Chatulbazar",
      "Kanaighat Sadar",
      "Lakhsmi Prasad",
      "Rajaganj",
    ],
    Moulvibazar: [
      "Akhailkura",
      "Bahar Mordan",
      "Banani",
      "Baralekha Baralekha",
      "Baralekha Dhakkhinbag",
      "Baralekha Juri",
      "Baralekha Purbashahabajpur",
      "Baronti",
      "Bhairabganj Bazar",
      "Borhat",
      "Borshijura",
      "Boruna",
      "Buddhimontopur",
      "Damia",
      "Dighirpar - Moulvibazar",
      "Durlovpur",
      "Ekatuna",
      "Ghumra",
      "Giasnagar",
      "Gobindopur",
      "Gujarai",
      "Hilalpur",
      "Jagatshi",
      "Jogonnathpur",
      "Jugidor",
      "Kadamhata",
      "Kalapur",
      "Kalenga",
      "Kamalganj",
      "Kamalganj Keramatnaga",
      "Kamalganj Munshibazar",
      "Kamalganj Patrakhola",
      "Kamalganj Shamsher Nagar",
      "Kamalpur Bazar",
      "Kazir Bazar",
      "Konokpur",
      "Kulaura Baramchal",
      "Kulaura Bhatera",
      "Kulaura Bhukshimail",
      "Kulaura Kajaldhara",
      "Kulaura Karimpur",
      "Kulaura Kulaura",
      "Kulaura Langla",
      "Kulaura Prithimpasha",
      "Kulaura Tillagaon",
      "Maliksorai",
      "Mamrokpur",
      "Moulvibazar - Islampur",
      "Moulvibazar Sadar",
      "Moulvibazar Sadar Afrozganj",
      "Moulvibazar Sadar Berirpar",
      "Moulvibazar Sadar Bonobithi",
      "Moulvibazar Sadar Chandinighat",
      "Moulvibazar Sadar Chowmuhona",
      "Moulvibazar Sadar Court Road",
      "Moulvibazar Sadar Darga Moholla",
      "Moulvibazar Sadar Dhaka Bus Stand",
      "Moulvibazar Sadar Dhorkapon",
      "Moulvibazar Sadar Kazirgaon",
      "Moulvibazar Sadar Kolimabad",
      "Moulvibazar Sadar Kusumbag",
      "Moulvibazar Sadar M. Saifur Rahman Road",
      "Moulvibazar Sadar Matarkapon",
      "Moulvibazar Sadar Monumukh",
      "Moulvibazar Sadar Mostafapur",
      "Moulvibazar Sadar Muslim Quarter",
      "Moulvibazar Sadar Old Hospital Road",
      "Moulvibazar Sadar Shah Mostafa Road",
      "Moulvibazar Sadar Shantibag",
      "Moulvibazar Sadar Sunapur",
      "Moulvibazar Sadar Syed Mujtoba Ali Road",
      "Moulvibazar Sadar Wapda Gate",
      "Mukambazar",
      "Munshi Bazar",
      "Nadampur",
      "Noldaria",
      "Police Line",
      "Polytechnic Institute",
      "Premnagar Tea Estate",
      "Radar Unit",
      "Raipur",
      "Rajnagar Fatehpur",
      "Rajnagar Munshibazar",
      "Rajnagar Sadar",
      "Rajnagar Tarapasha",
      "Rajnagar Tengra",
      "Roghunondonpur",
      "Sabia",
      "Sarkarbazar",
      "Shah Bandar",
      "Shamorkuna",
      "Sherpur Bus Stand",
      "Shompashi",
      "Shomserganj",
      "Shomsernagar",
      "Shomsernagar Airport",
      "Soiyarpur",
      "Sreemangal",
      "Sreemangal Kalighat",
      "Sreemangal Khejurichhara",
      "Sreemangal Narain Chora",
      "Sreemangal Satgaon",
      "Sunapur",
      "Taltola Baramchal",
      "Thana Bazar",
      "Uluail",
      "Uttor Mulaim",
    ],
    Sunamganj: [
      "Bishwamvarpur",
      "Chhatak",
      "Chhatak Cement Factory",
      "Chhatak Chourangi Bazar",
      "Chhatak Gabindaganj",
      "Chhatak Gabindaganj Natun Bazar",
      "Chhatak Islamabad",
      "Chhatak jahidpur",
      "Chhatak Khurma",
      "Chhatak Moinpur",
      "Chhatak Paper Mills",
      "Derai Chandpur",
      "Derai Sadar",
      "Dowarabazar",
      "Ghungiar",
      "Jagannathpur Sadar",
      "Jagnnathpur Atuajan",
      "Jagnnathpur Hasan Fatemapur",
      "Jagnnathpur Rasulganj",
      "Jagnnathpur Shiramsi",
      "Jagnnathpur Syedpur",
      "Jamalganj",
      "Rangarchar",
      "Sachna",
      "Selborash",
      "Sunamganj Civil Surgeon Office",
      "Sunamganj Madhyanagar",
      "Sunamganj Sadar Hospital",
      "Sunamganj Sadar Pagla",
      "Sunamganj Sadar Patharia",
      "Sunamganj Sadar Sunamganj Sadar",
      "Surma",
      "Tahirpur",
      "Tarol",
    ],
    "Sylhet Sadar": [
      "Akhalia",
      "Alampur",
      "Ambarkhana",
      "Badam Bagicha",
      "Baghibari",
      "Bhatalia",
      "Bil Par",
      "Bimanbondarair Road",
      "Boroikandi",
      "Charadigirpar",
      "Chondan Tula",
      "Choukidighi",
      "Daptari Para",
      "Dargah Mahalla",
      "Darjee Band",
      "Dattapara",
      "Gasitula",
      "Golapganj",
      "Haripur",
      "Hatimbagh",
      "Hauldar Para",
      "Hawapara",
      "Jalalabad",
      "Jalalabad Cantonment",
      "Jamtala",
      "Jherjheri Para",
      "Jointapur",
      "Kahar Para",
      "Kajal Shah",
      "Kalapara",
      "Kalighat",
      "Kamalbazer",
      "Kanisail",
      "Kazi Jalaluddin Mahalla",
      "Keyapara",
      "Khadimnagar",
      "Khadim Para",
      "Kharadi Para",
      "Khasdobir",
      "Khujarkhola",
      "Korarpar",
      "Kuarpar",
      "Kuliapara",
      "Kurshi Ghat",
      "Lakri Para",
      "Lala Bazar",
      "Lalbazar",
      "Lal Dighirpar",
      "Lama Bazar",
      "Lawai",
      "Majumder Para",
      "Mazumdari",
      "Mirapara",
      "Mir Boxtula",
      "Mirza Jangal",
      "Modhu Shahid",
      "Mominkhola",
      "Mongla",
      "Mulla Para",
      "Munshipara",
      "Nabab Road",
      "Nehari Para",
      "Noapara",
      "Pathan Tula",
      "Pir Mahalla",
      "Ponitula",
      "Puran Lane",
      "Rajargali",
      "Raj Bari",
      "Rajpara",
      "Ranga Hajiganj",
      "Sabuj Bagh",
      "Sadatikar",
      "Sadipur",
      "Sagardigir Par",
      "Sarderpar",
      "Shahajalal University Sylhet",
      "Shah Jalal University (SUST-Akaliya)",
      "Shaplabagh",
      "Shenpara",
      "Shibganj - Khoradi Para",
      "Silam",
      "Sylhet Biman Bondar",
      "Sylhet - Kadamtali",
      "Sylhet Sadar Upazilla Office",
      "Taltola Road",
      "Tero Ratan",
      "Tilagor - Tatipara",
    ],
  },
};

const convertToSnakeCase = (str) => {
  // Remove parentheses
  const noParenthesesStr = str.replace(/[()]/g, "");

  // Replace hyphens with underscores
  const underscoredStr = noParenthesesStr.replace(/-/g, "_");

  // Split words by spaces and convert to camelCase
  const words = underscoredStr.split(" ");
  const camelCaseWords = words.map((word, index) => {
    // First word should be all lowercase
    if (index === 0) {
      return word.toLowerCase();
    }
    // Other words should be capitalized
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  });

  // Join words into a single string
  const camelCaseStr = camelCaseWords.join("");

  return camelCaseStr;
};

const dataSaver = async (domainName) => {
  let file;

  if (fs.existsSync(`./lavel-1.json`)) {
    console.log("existsSync");
    file = JSON.parse(fs.readFileSync(`./lavel-1.json`));
  } else {
    console.log("NO EXIST");
    file = [];
  }

  console.log(file);

  file.push(domainName);

  fs.writeFile(`lavel-1.json`, JSON.stringify(file), (err) => {
    if (err) {
      console.log("ERROR: ", err);
    }
  });
};

const GetDataForProvince = () => {
  let response = [];

  Object.entries(data)?.map((item, index) => {
    const dataToBuild = {
      id: `${index}`,
      name: item[0],
      slug: convertToSnakeCase(item[0]),
    };

    response.push(dataToBuild);
  });

  dataSaver(response);
};

const GetDataForCities = () => {
  let response = [];

  Object.entries(data)?.map((item, index) => {
    Object.entries(item[1])?.map((item2, index2) => {
      //This is for Stage 2
      const dataToBuild = {
        id: `${index2}${index}`,
        name: item2[0],
        slug: convertToSnakeCase(item2[0]),
        parentId: `${index}`,
      };
      response.push(dataToBuild);
    });
  });

  dataSaver(response);
};
const GetDataForAreas = () => {
  let response = [];

  Object.entries(data)?.map((item, index) => {
    Object.entries(item[1])?.map((item2, index2) => {
      Object.entries(item2[1])?.map((item3, index3) => {
        const dataToBuild = {
          id: `${index3}${index2}${index}`,
          name: item3[1],
          slug: convertToSnakeCase(item3[1]),
          parentId: `${index2}${index}`,
        };
        response.push(dataToBuild);
      });
    });
  });

  dataSaver(response);
};

// GetDataForProvince();
// GetDataForCities();
// GetDataForAreas();
